// Code generated by ent, DO NOT EDIT.

package notifychat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the notifychat type in the database.
	Label = "notify_chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPeerType holds the string denoting the peer_type field in the database.
	FieldPeerType = "peer_type"
	// FieldPeerID holds the string denoting the peer_id field in the database.
	FieldPeerID = "peer_id"
	// FieldAccessHash holds the string denoting the access_hash field in the database.
	FieldAccessHash = "access_hash"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldAddedBy holds the string denoting the added_by field in the database.
	FieldAddedBy = "added_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the notifychat in the database.
	Table = "notify_chats"
)

// Columns holds all SQL columns for notifychat fields.
var Columns = []string{
	FieldID,
	FieldPeerType,
	FieldPeerID,
	FieldAccessHash,
	FieldTitle,
	FieldEnabled,
	FieldAddedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPeerType holds the default value on creation for the "peer_type" field.
	DefaultPeerType string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the NotifyChat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPeerType orders the results by the peer_type field.
func ByPeerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeerType, opts...).ToFunc()
}

// ByPeerID orders the results by the peer_id field.
func ByPeerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeerID, opts...).ToFunc()
}

// ByAccessHash orders the results by the access_hash field.
func ByAccessHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessHash, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByAddedBy orders the results by the added_by field.
func ByAddedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
