// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the chunk type in the database.
	Label = "chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDocumentID holds the string denoting the document_id field in the database.
	FieldDocumentID = "document_id"
	// FieldChunkIndex holds the string denoting the chunk_index field in the database.
	FieldChunkIndex = "chunk_index"
	// FieldChunkType holds the string denoting the chunk_type field in the database.
	FieldChunkType = "chunk_type"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldTextHash holds the string denoting the text_hash field in the database.
	FieldTextHash = "text_hash"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTokenCount holds the string denoting the token_count field in the database.
	FieldTokenCount = "token_count"
	// FieldQdrantPointID holds the string denoting the qdrant_point_id field in the database.
	FieldQdrantPointID = "qdrant_point_id"
	// EdgeDocument holds the string denoting the document edge name in mutations.
	EdgeDocument = "document"
	// Table holds the table name of the chunk in the database.
	Table = "chunks"
	// DocumentTable is the table that holds the document relation/edge.
	DocumentTable = "chunks"
	// DocumentInverseTable is the table name for the Document entity.
	// It exists in this package in order to avoid circular dependency with the "document" package.
	DocumentInverseTable = "documents"
	// DocumentColumn is the table column denoting the document relation/edge.
	DocumentColumn = "document_id"
)

// Columns holds all SQL columns for chunk fields.
var Columns = []string{
	FieldID,
	FieldDocumentID,
	FieldChunkIndex,
	FieldChunkType,
	FieldTitle,
	FieldText,
	FieldTextHash,
	FieldMetadata,
	FieldTokenCount,
	FieldQdrantPointID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ChunkTypeValidator is a validator for the "chunk_type" field. It is called by the builders before save.
	ChunkTypeValidator func(string) error
	// TextValidator is a validator for the "text" field. It is called by the builders before save.
	TextValidator func(string) error
	// TextHashValidator is a validator for the "text_hash" field. It is called by the builders before save.
	TextHashValidator func(string) error
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Chunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDocumentID orders the results by the document_id field.
func ByDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentID, opts...).ToFunc()
}

// ByChunkIndex orders the results by the chunk_index field.
func ByChunkIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkIndex, opts...).ToFunc()
}

// ByChunkType orders the results by the chunk_type field.
func ByChunkType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkType, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByTextHash orders the results by the text_hash field.
func ByTextHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTextHash, opts...).ToFunc()
}

// ByTokenCount orders the results by the token_count field.
func ByTokenCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenCount, opts...).ToFunc()
}

// ByQdrantPointID orders the results by the qdrant_point_id field.
func ByQdrantPointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQdrantPointID, opts...).ToFunc()
}

// ByDocumentField orders the results by document field.
func ByDocumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentStep(), sql.OrderByField(field, opts...))
	}
}
func newDocumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
	)
}
