// Code generated by ent, DO NOT EDIT.

package chunk

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"

	"github.com/go-faster/sisyphus/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldID, id))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldDocumentID, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkType applies equality check predicate on the "chunk_type" field. It's identical to ChunkTypeEQ.
func ChunkType(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkType, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTitle, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldText, v))
}

// TextHash applies equality check predicate on the "text_hash" field. It's identical to TextHashEQ.
func TextHash(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTextHash, v))
}

// TokenCount applies equality check predicate on the "token_count" field. It's identical to TokenCountEQ.
func TokenCount(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTokenCount, v))
}

// QdrantPointID applies equality check predicate on the "qdrant_point_id" field. It's identical to QdrantPointIDEQ.
func QdrantPointID(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldQdrantPointID, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldDocumentID, vs...))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ChunkTypeEQ applies the EQ predicate on the "chunk_type" field.
func ChunkTypeEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldChunkType, v))
}

// ChunkTypeNEQ applies the NEQ predicate on the "chunk_type" field.
func ChunkTypeNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldChunkType, v))
}

// ChunkTypeIn applies the In predicate on the "chunk_type" field.
func ChunkTypeIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldChunkType, vs...))
}

// ChunkTypeNotIn applies the NotIn predicate on the "chunk_type" field.
func ChunkTypeNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldChunkType, vs...))
}

// ChunkTypeGT applies the GT predicate on the "chunk_type" field.
func ChunkTypeGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldChunkType, v))
}

// ChunkTypeGTE applies the GTE predicate on the "chunk_type" field.
func ChunkTypeGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldChunkType, v))
}

// ChunkTypeLT applies the LT predicate on the "chunk_type" field.
func ChunkTypeLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldChunkType, v))
}

// ChunkTypeLTE applies the LTE predicate on the "chunk_type" field.
func ChunkTypeLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldChunkType, v))
}

// ChunkTypeContains applies the Contains predicate on the "chunk_type" field.
func ChunkTypeContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldChunkType, v))
}

// ChunkTypeHasPrefix applies the HasPrefix predicate on the "chunk_type" field.
func ChunkTypeHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldChunkType, v))
}

// ChunkTypeHasSuffix applies the HasSuffix predicate on the "chunk_type" field.
func ChunkTypeHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldChunkType, v))
}

// ChunkTypeEqualFold applies the EqualFold predicate on the "chunk_type" field.
func ChunkTypeEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldChunkType, v))
}

// ChunkTypeContainsFold applies the ContainsFold predicate on the "chunk_type" field.
func ChunkTypeContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldChunkType, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldTitle, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldText, v))
}

// TextHashEQ applies the EQ predicate on the "text_hash" field.
func TextHashEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTextHash, v))
}

// TextHashNEQ applies the NEQ predicate on the "text_hash" field.
func TextHashNEQ(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldTextHash, v))
}

// TextHashIn applies the In predicate on the "text_hash" field.
func TextHashIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldTextHash, vs...))
}

// TextHashNotIn applies the NotIn predicate on the "text_hash" field.
func TextHashNotIn(vs ...string) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldTextHash, vs...))
}

// TextHashGT applies the GT predicate on the "text_hash" field.
func TextHashGT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldTextHash, v))
}

// TextHashGTE applies the GTE predicate on the "text_hash" field.
func TextHashGTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldTextHash, v))
}

// TextHashLT applies the LT predicate on the "text_hash" field.
func TextHashLT(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldTextHash, v))
}

// TextHashLTE applies the LTE predicate on the "text_hash" field.
func TextHashLTE(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldTextHash, v))
}

// TextHashContains applies the Contains predicate on the "text_hash" field.
func TextHashContains(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContains(FieldTextHash, v))
}

// TextHashHasPrefix applies the HasPrefix predicate on the "text_hash" field.
func TextHashHasPrefix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasPrefix(FieldTextHash, v))
}

// TextHashHasSuffix applies the HasSuffix predicate on the "text_hash" field.
func TextHashHasSuffix(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldHasSuffix(FieldTextHash, v))
}

// TextHashEqualFold applies the EqualFold predicate on the "text_hash" field.
func TextHashEqualFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldEqualFold(FieldTextHash, v))
}

// TextHashContainsFold applies the ContainsFold predicate on the "text_hash" field.
func TextHashContainsFold(v string) predicate.Chunk {
	return predicate.Chunk(sql.FieldContainsFold(FieldTextHash, v))
}

// TokenCountEQ applies the EQ predicate on the "token_count" field.
func TokenCountEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldTokenCount, v))
}

// TokenCountNEQ applies the NEQ predicate on the "token_count" field.
func TokenCountNEQ(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldTokenCount, v))
}

// TokenCountIn applies the In predicate on the "token_count" field.
func TokenCountIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldTokenCount, vs...))
}

// TokenCountNotIn applies the NotIn predicate on the "token_count" field.
func TokenCountNotIn(vs ...int) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldTokenCount, vs...))
}

// TokenCountGT applies the GT predicate on the "token_count" field.
func TokenCountGT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldTokenCount, v))
}

// TokenCountGTE applies the GTE predicate on the "token_count" field.
func TokenCountGTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldTokenCount, v))
}

// TokenCountLT applies the LT predicate on the "token_count" field.
func TokenCountLT(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldTokenCount, v))
}

// TokenCountLTE applies the LTE predicate on the "token_count" field.
func TokenCountLTE(v int) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldTokenCount, v))
}

// TokenCountIsNil applies the IsNil predicate on the "token_count" field.
func TokenCountIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldTokenCount))
}

// TokenCountNotNil applies the NotNil predicate on the "token_count" field.
func TokenCountNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldTokenCount))
}

// QdrantPointIDEQ applies the EQ predicate on the "qdrant_point_id" field.
func QdrantPointIDEQ(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldEQ(FieldQdrantPointID, v))
}

// QdrantPointIDNEQ applies the NEQ predicate on the "qdrant_point_id" field.
func QdrantPointIDNEQ(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNEQ(FieldQdrantPointID, v))
}

// QdrantPointIDIn applies the In predicate on the "qdrant_point_id" field.
func QdrantPointIDIn(vs ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldIn(FieldQdrantPointID, vs...))
}

// QdrantPointIDNotIn applies the NotIn predicate on the "qdrant_point_id" field.
func QdrantPointIDNotIn(vs ...uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldNotIn(FieldQdrantPointID, vs...))
}

// QdrantPointIDGT applies the GT predicate on the "qdrant_point_id" field.
func QdrantPointIDGT(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGT(FieldQdrantPointID, v))
}

// QdrantPointIDGTE applies the GTE predicate on the "qdrant_point_id" field.
func QdrantPointIDGTE(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldGTE(FieldQdrantPointID, v))
}

// QdrantPointIDLT applies the LT predicate on the "qdrant_point_id" field.
func QdrantPointIDLT(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLT(FieldQdrantPointID, v))
}

// QdrantPointIDLTE applies the LTE predicate on the "qdrant_point_id" field.
func QdrantPointIDLTE(v uuid.UUID) predicate.Chunk {
	return predicate.Chunk(sql.FieldLTE(FieldQdrantPointID, v))
}

// QdrantPointIDIsNil applies the IsNil predicate on the "qdrant_point_id" field.
func QdrantPointIDIsNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldIsNull(FieldQdrantPointID))
}

// QdrantPointIDNotNil applies the NotNil predicate on the "qdrant_point_id" field.
func QdrantPointIDNotNil() predicate.Chunk {
	return predicate.Chunk(sql.FieldNotNull(FieldQdrantPointID))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.Document) predicate.Chunk {
	return predicate.Chunk(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chunk) predicate.Chunk {
	return predicate.Chunk(sql.NotPredicates(p))
}
