// Code generated by ent, DO NOT EDIT.

package supportrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"

	"github.com/go-faster/sisyphus/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldID, id))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldChatID, v))
}

// FirstMessageID applies equality check predicate on the "first_message_id" field. It's identical to FirstMessageIDEQ.
func FirstMessageID(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldFirstMessageID, v))
}

// LastMessageID applies equality check predicate on the "last_message_id" field. It's identical to LastMessageIDEQ.
func LastMessageID(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldLastMessageID, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSourceURL, v))
}

// RawText applies equality check predicate on the "raw_text" field. It's identical to RawTextEQ.
func RawText(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldRawText, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSummary, v))
}

// ServiceGuess applies equality check predicate on the "service_guess" field. It's identical to ServiceGuessEQ.
func ServiceGuess(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldServiceGuess, v))
}

// SeverityGuess applies equality check predicate on the "severity_guess" field. It's identical to SeverityGuessEQ.
func SeverityGuess(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSeverityGuess, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldStatus, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldConfidence, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldChatID, v))
}

// FirstMessageIDEQ applies the EQ predicate on the "first_message_id" field.
func FirstMessageIDEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldFirstMessageID, v))
}

// FirstMessageIDNEQ applies the NEQ predicate on the "first_message_id" field.
func FirstMessageIDNEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldFirstMessageID, v))
}

// FirstMessageIDIn applies the In predicate on the "first_message_id" field.
func FirstMessageIDIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldFirstMessageID, vs...))
}

// FirstMessageIDNotIn applies the NotIn predicate on the "first_message_id" field.
func FirstMessageIDNotIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldFirstMessageID, vs...))
}

// FirstMessageIDGT applies the GT predicate on the "first_message_id" field.
func FirstMessageIDGT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldFirstMessageID, v))
}

// FirstMessageIDGTE applies the GTE predicate on the "first_message_id" field.
func FirstMessageIDGTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldFirstMessageID, v))
}

// FirstMessageIDLT applies the LT predicate on the "first_message_id" field.
func FirstMessageIDLT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldFirstMessageID, v))
}

// FirstMessageIDLTE applies the LTE predicate on the "first_message_id" field.
func FirstMessageIDLTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldFirstMessageID, v))
}

// LastMessageIDEQ applies the EQ predicate on the "last_message_id" field.
func LastMessageIDEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldLastMessageID, v))
}

// LastMessageIDNEQ applies the NEQ predicate on the "last_message_id" field.
func LastMessageIDNEQ(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldLastMessageID, v))
}

// LastMessageIDIn applies the In predicate on the "last_message_id" field.
func LastMessageIDIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldLastMessageID, vs...))
}

// LastMessageIDNotIn applies the NotIn predicate on the "last_message_id" field.
func LastMessageIDNotIn(vs ...int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldLastMessageID, vs...))
}

// LastMessageIDGT applies the GT predicate on the "last_message_id" field.
func LastMessageIDGT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldLastMessageID, v))
}

// LastMessageIDGTE applies the GTE predicate on the "last_message_id" field.
func LastMessageIDGTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldLastMessageID, v))
}

// LastMessageIDLT applies the LT predicate on the "last_message_id" field.
func LastMessageIDLT(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldLastMessageID, v))
}

// LastMessageIDLTE applies the LTE predicate on the "last_message_id" field.
func LastMessageIDLTE(v int64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldLastMessageID, v))
}

// LastMessageIDIsNil applies the IsNil predicate on the "last_message_id" field.
func LastMessageIDIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldLastMessageID))
}

// LastMessageIDNotNil applies the NotNil predicate on the "last_message_id" field.
func LastMessageIDNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldLastMessageID))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldSourceURL, v))
}

// RawTextEQ applies the EQ predicate on the "raw_text" field.
func RawTextEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldRawText, v))
}

// RawTextNEQ applies the NEQ predicate on the "raw_text" field.
func RawTextNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldRawText, v))
}

// RawTextIn applies the In predicate on the "raw_text" field.
func RawTextIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldRawText, vs...))
}

// RawTextNotIn applies the NotIn predicate on the "raw_text" field.
func RawTextNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldRawText, vs...))
}

// RawTextGT applies the GT predicate on the "raw_text" field.
func RawTextGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldRawText, v))
}

// RawTextGTE applies the GTE predicate on the "raw_text" field.
func RawTextGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldRawText, v))
}

// RawTextLT applies the LT predicate on the "raw_text" field.
func RawTextLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldRawText, v))
}

// RawTextLTE applies the LTE predicate on the "raw_text" field.
func RawTextLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldRawText, v))
}

// RawTextContains applies the Contains predicate on the "raw_text" field.
func RawTextContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldRawText, v))
}

// RawTextHasPrefix applies the HasPrefix predicate on the "raw_text" field.
func RawTextHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldRawText, v))
}

// RawTextHasSuffix applies the HasSuffix predicate on the "raw_text" field.
func RawTextHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldRawText, v))
}

// RawTextEqualFold applies the EqualFold predicate on the "raw_text" field.
func RawTextEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldRawText, v))
}

// RawTextContainsFold applies the ContainsFold predicate on the "raw_text" field.
func RawTextContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldRawText, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryIsNil applies the IsNil predicate on the "summary" field.
func SummaryIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldSummary))
}

// SummaryNotNil applies the NotNil predicate on the "summary" field.
func SummaryNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldSummary))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldSummary, v))
}

// ServiceGuessEQ applies the EQ predicate on the "service_guess" field.
func ServiceGuessEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldServiceGuess, v))
}

// ServiceGuessNEQ applies the NEQ predicate on the "service_guess" field.
func ServiceGuessNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldServiceGuess, v))
}

// ServiceGuessIn applies the In predicate on the "service_guess" field.
func ServiceGuessIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldServiceGuess, vs...))
}

// ServiceGuessNotIn applies the NotIn predicate on the "service_guess" field.
func ServiceGuessNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldServiceGuess, vs...))
}

// ServiceGuessGT applies the GT predicate on the "service_guess" field.
func ServiceGuessGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldServiceGuess, v))
}

// ServiceGuessGTE applies the GTE predicate on the "service_guess" field.
func ServiceGuessGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldServiceGuess, v))
}

// ServiceGuessLT applies the LT predicate on the "service_guess" field.
func ServiceGuessLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldServiceGuess, v))
}

// ServiceGuessLTE applies the LTE predicate on the "service_guess" field.
func ServiceGuessLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldServiceGuess, v))
}

// ServiceGuessContains applies the Contains predicate on the "service_guess" field.
func ServiceGuessContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldServiceGuess, v))
}

// ServiceGuessHasPrefix applies the HasPrefix predicate on the "service_guess" field.
func ServiceGuessHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldServiceGuess, v))
}

// ServiceGuessHasSuffix applies the HasSuffix predicate on the "service_guess" field.
func ServiceGuessHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldServiceGuess, v))
}

// ServiceGuessIsNil applies the IsNil predicate on the "service_guess" field.
func ServiceGuessIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldServiceGuess))
}

// ServiceGuessNotNil applies the NotNil predicate on the "service_guess" field.
func ServiceGuessNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldServiceGuess))
}

// ServiceGuessEqualFold applies the EqualFold predicate on the "service_guess" field.
func ServiceGuessEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldServiceGuess, v))
}

// ServiceGuessContainsFold applies the ContainsFold predicate on the "service_guess" field.
func ServiceGuessContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldServiceGuess, v))
}

// SeverityGuessEQ applies the EQ predicate on the "severity_guess" field.
func SeverityGuessEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldSeverityGuess, v))
}

// SeverityGuessNEQ applies the NEQ predicate on the "severity_guess" field.
func SeverityGuessNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldSeverityGuess, v))
}

// SeverityGuessIn applies the In predicate on the "severity_guess" field.
func SeverityGuessIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldSeverityGuess, vs...))
}

// SeverityGuessNotIn applies the NotIn predicate on the "severity_guess" field.
func SeverityGuessNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldSeverityGuess, vs...))
}

// SeverityGuessGT applies the GT predicate on the "severity_guess" field.
func SeverityGuessGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldSeverityGuess, v))
}

// SeverityGuessGTE applies the GTE predicate on the "severity_guess" field.
func SeverityGuessGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldSeverityGuess, v))
}

// SeverityGuessLT applies the LT predicate on the "severity_guess" field.
func SeverityGuessLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldSeverityGuess, v))
}

// SeverityGuessLTE applies the LTE predicate on the "severity_guess" field.
func SeverityGuessLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldSeverityGuess, v))
}

// SeverityGuessContains applies the Contains predicate on the "severity_guess" field.
func SeverityGuessContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldSeverityGuess, v))
}

// SeverityGuessHasPrefix applies the HasPrefix predicate on the "severity_guess" field.
func SeverityGuessHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldSeverityGuess, v))
}

// SeverityGuessHasSuffix applies the HasSuffix predicate on the "severity_guess" field.
func SeverityGuessHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldSeverityGuess, v))
}

// SeverityGuessIsNil applies the IsNil predicate on the "severity_guess" field.
func SeverityGuessIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldSeverityGuess))
}

// SeverityGuessNotNil applies the NotNil predicate on the "severity_guess" field.
func SeverityGuessNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldSeverityGuess))
}

// SeverityGuessEqualFold applies the EqualFold predicate on the "severity_guess" field.
func SeverityGuessEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldSeverityGuess, v))
}

// SeverityGuessContainsFold applies the ContainsFold predicate on the "severity_guess" field.
func SeverityGuessContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldSeverityGuess, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldContainsFold(FieldStatus, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldConfidence, v))
}

// ConfidenceIsNil applies the IsNil predicate on the "confidence" field.
func ConfidenceIsNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIsNull(FieldConfidence))
}

// ConfidenceNotNil applies the NotNil predicate on the "confidence" field.
func ConfidenceNotNil() predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotNull(FieldConfidence))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupportRequest {
	return predicate.SupportRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupportRequest) predicate.SupportRequest {
	return predicate.SupportRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupportRequest) predicate.SupportRequest {
	return predicate.SupportRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupportRequest) predicate.SupportRequest {
	return predicate.SupportRequest(sql.NotPredicates(p))
}
