// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChunksColumns holds the columns for the "chunks" table.
	ChunksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "chunk_index", Type: field.TypeInt},
		{Name: "chunk_type", Type: field.TypeString},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "text_hash", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON, Default: "{}"},
		{Name: "token_count", Type: field.TypeInt, Nullable: true},
		{Name: "qdrant_point_id", Type: field.TypeUUID, Nullable: true},
		{Name: "document_id", Type: field.TypeUUID},
	}
	// ChunksTable holds the schema information for the "chunks" table.
	ChunksTable = &schema.Table{
		Name:       "chunks",
		Columns:    ChunksColumns,
		PrimaryKey: []*schema.Column{ChunksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chunks_documents_chunks",
				Columns:    []*schema.Column{ChunksColumns[9]},
				RefColumns: []*schema.Column{DocumentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "chunk_document_id_chunk_index_text_hash",
				Unique:  true,
				Columns: []*schema.Column{ChunksColumns[9], ChunksColumns[1], ChunksColumns[5]},
			},
			{
				Name:    "chunk_metadata",
				Unique:  false,
				Columns: []*schema.Column{ChunksColumns[6]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
		},
	}
	// DocumentsColumns holds the columns for the "documents" table.
	DocumentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "source", Type: field.TypeString},
		{Name: "source_id", Type: field.TypeString},
		{Name: "source_url", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "body_hash", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON, Default: "{}"},
		{Name: "chunker_version", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true},
		{Name: "captured_at", Type: field.TypeTime},
	}
	// DocumentsTable holds the schema information for the "documents" table.
	DocumentsTable = &schema.Table{
		Name:       "documents",
		Columns:    DocumentsColumns,
		PrimaryKey: []*schema.Column{DocumentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "document_source_source_id",
				Unique:  true,
				Columns: []*schema.Column{DocumentsColumns[1], DocumentsColumns[2]},
			},
			{
				Name:    "document_metadata",
				Unique:  false,
				Columns: []*schema.Column{DocumentsColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
		},
	}
	// InvestigationJobsColumns holds the columns for the "investigation_jobs" table.
	InvestigationJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "report", Type: field.TypeJSON, Nullable: true},
		{Name: "iterations", Type: field.TypeInt, Default: 0},
		{Name: "tools_used", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// InvestigationJobsTable holds the schema information for the "investigation_jobs" table.
	InvestigationJobsTable = &schema.Table{
		Name:       "investigation_jobs",
		Columns:    InvestigationJobsColumns,
		PrimaryKey: []*schema.Column{InvestigationJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "investigationjob_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{InvestigationJobsColumns[1]},
			},
			{
				Name:    "investigationjob_status",
				Unique:  false,
				Columns: []*schema.Column{InvestigationJobsColumns[3]},
			},
		},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "dedup_key", Type: field.TypeString},
		{Name: "channel", Type: field.TypeString},
		{Name: "telegram_user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "telegram_access_hash", Type: field.TypeInt64, Nullable: true},
		{Name: "source", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "delivered_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notifications_users_notifications",
				Columns:    []*schema.Column{NotificationsColumns[15]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notification_dedup_key",
				Unique:  true,
				Columns: []*schema.Column{NotificationsColumns[1]},
			},
			{
				Name:    "notification_status",
				Unique:  false,
				Columns: []*schema.Column{NotificationsColumns[9]},
			},
		},
	}
	// NotifySubscriptionsColumns holds the columns for the "notify_subscriptions" table.
	NotifySubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "source", Type: field.TypeString},
		{Name: "event_types", Type: field.TypeJSON},
		{Name: "filters", Type: field.TypeJSON, Default: "{}"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// NotifySubscriptionsTable holds the schema information for the "notify_subscriptions" table.
	NotifySubscriptionsTable = &schema.Table{
		Name:       "notify_subscriptions",
		Columns:    NotifySubscriptionsColumns,
		PrimaryKey: []*schema.Column{NotifySubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "notify_subscriptions_users_subscriptions",
				Columns:    []*schema.Column{NotifySubscriptionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "notifysubscription_user_id_source",
				Unique:  true,
				Columns: []*schema.Column{NotifySubscriptionsColumns[7], NotifySubscriptionsColumns[1]},
			},
			{
				Name:    "notifysubscription_filters",
				Unique:  false,
				Columns: []*schema.Column{NotifySubscriptionsColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Type: "GIN",
				},
			},
		},
	}
	// QueueJobsColumns holds the columns for the "queue_jobs" table.
	QueueJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "queue", Type: field.TypeString},
		{Name: "dedup_key", Type: field.TypeString},
		{Name: "payload", Type: field.TypeBytes, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "max_attempts", Type: field.TypeInt, Default: 5},
		{Name: "visible_at", Type: field.TypeTime},
		{Name: "lease_owner", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
	}
	// QueueJobsTable holds the schema information for the "queue_jobs" table.
	QueueJobsTable = &schema.Table{
		Name:       "queue_jobs",
		Columns:    QueueJobsColumns,
		PrimaryKey: []*schema.Column{QueueJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "queuejob_queue_dedup_key",
				Unique:  true,
				Columns: []*schema.Column{QueueJobsColumns[1], QueueJobsColumns[2]},
			},
			{
				Name:    "queuejob_queue_visible_at",
				Unique:  false,
				Columns: []*schema.Column{QueueJobsColumns[1], QueueJobsColumns[7]},
				Annotation: &entsql.IndexAnnotation{
					Where: "status IN ('pending', 'running')",
				},
			},
		},
	}
	// SupportRequestsColumns holds the columns for the "support_requests" table.
	SupportRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "first_message_id", Type: field.TypeInt64},
		{Name: "last_message_id", Type: field.TypeInt64, Nullable: true},
		{Name: "source_url", Type: field.TypeString, Nullable: true},
		{Name: "raw_text", Type: field.TypeString, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "service_guess", Type: field.TypeString, Nullable: true},
		{Name: "severity_guess", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "new"},
		{Name: "confidence", Type: field.TypeFloat64, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Default: "{}"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SupportRequestsTable holds the schema information for the "support_requests" table.
	SupportRequestsTable = &schema.Table{
		Name:       "support_requests",
		Columns:    SupportRequestsColumns,
		PrimaryKey: []*schema.Column{SupportRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "supportrequest_chat_id_first_message_id",
				Unique:  true,
				Columns: []*schema.Column{SupportRequestsColumns[1], SupportRequestsColumns[2]},
			},
			{
				Name:    "supportrequest_status",
				Unique:  false,
				Columns: []*schema.Column{SupportRequestsColumns[9]},
			},
		},
	}
	// SyncStatesColumns holds the columns for the "sync_states" table.
	SyncStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "source", Type: field.TypeString},
		{Name: "last_synced_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_cursor", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "new"},
		{Name: "error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "document_count", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SyncStatesTable holds the schema information for the "sync_states" table.
	SyncStatesTable = &schema.Table{
		Name:       "sync_states",
		Columns:    SyncStatesColumns,
		PrimaryKey: []*schema.Column{SyncStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "syncstate_source",
				Unique:  true,
				Columns: []*schema.Column{SyncStatesColumns[1]},
			},
			{
				Name:    "syncstate_status",
				Unique:  false,
				Columns: []*schema.Column{SyncStatesColumns[4]},
			},
		},
	}
	// TelegramMessagesColumns holds the columns for the "telegram_messages" table.
	TelegramMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "message_id", Type: field.TypeInt64},
		{Name: "thread_id", Type: field.TypeInt64, Nullable: true},
		{Name: "sender_id", Type: field.TypeInt64, Nullable: true},
		{Name: "sender_name", Type: field.TypeString, Nullable: true},
		{Name: "text", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "message_date", Type: field.TypeTime},
		{Name: "reply_to_id", Type: field.TypeInt64, Nullable: true},
		{Name: "raw_json", Type: field.TypeJSON, Default: "{}"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TelegramMessagesTable holds the schema information for the "telegram_messages" table.
	TelegramMessagesTable = &schema.Table{
		Name:       "telegram_messages",
		Columns:    TelegramMessagesColumns,
		PrimaryKey: []*schema.Column{TelegramMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "telegrammessage_chat_id_message_id",
				Unique:  true,
				Columns: []*schema.Column{TelegramMessagesColumns[1], TelegramMessagesColumns[2]},
			},
			{
				Name:    "telegrammessage_chat_id_message_date",
				Unique:  false,
				Columns: []*schema.Column{TelegramMessagesColumns[1], TelegramMessagesColumns[7]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "telegram_user_id", Type: field.TypeInt64},
		{Name: "telegram_access_hash", Type: field.TypeInt64, Nullable: true},
		{Name: "gitlab_username", Type: field.TypeString, Nullable: true},
		{Name: "jira_account_id", Type: field.TypeString, Nullable: true},
		{Name: "jira_display_name", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_telegram_user_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_gitlab_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_jira_account_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// UserTokensColumns holds the columns for the "user_tokens" table.
	UserTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "token_hash", Type: field.TypeString},
		{Name: "token_prefix", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserTokensTable holds the schema information for the "user_tokens" table.
	UserTokensTable = &schema.Table{
		Name:       "user_tokens",
		Columns:    UserTokensColumns,
		PrimaryKey: []*schema.Column{UserTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_tokens_users_tokens",
				Columns:    []*schema.Column{UserTokensColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "usertoken_token_hash",
				Unique:  true,
				Columns: []*schema.Column{UserTokensColumns[2]},
			},
			{
				Name:    "usertoken_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserTokensColumns[8]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChunksTable,
		DocumentsTable,
		InvestigationJobsTable,
		NotificationsTable,
		NotifySubscriptionsTable,
		QueueJobsTable,
		SupportRequestsTable,
		SyncStatesTable,
		TelegramMessagesTable,
		UsersTable,
		UserTokensTable,
	}
)

func init() {
	ChunksTable.ForeignKeys[0].RefTable = DocumentsTable
	NotificationsTable.ForeignKeys[0].RefTable = UsersTable
	NotifySubscriptionsTable.ForeignKeys[0].RefTable = UsersTable
	UserTokensTable.ForeignKeys[0].RefTable = UsersTable
}
