// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/sisyphus/internal/ent/chunk"
	"github.com/go-faster/sisyphus/internal/ent/document"
	"github.com/google/uuid"
)

// ChunkCreate is the builder for creating a Chunk entity.
type ChunkCreate struct {
	config
	mutation *ChunkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDocumentID sets the "document_id" field.
func (_c *ChunkCreate) SetDocumentID(v uuid.UUID) *ChunkCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetChunkIndex sets the "chunk_index" field.
func (_c *ChunkCreate) SetChunkIndex(v int) *ChunkCreate {
	_c.mutation.SetChunkIndex(v)
	return _c
}

// SetChunkType sets the "chunk_type" field.
func (_c *ChunkCreate) SetChunkType(v string) *ChunkCreate {
	_c.mutation.SetChunkType(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ChunkCreate) SetTitle(v string) *ChunkCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableTitle(v *string) *ChunkCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *ChunkCreate) SetText(v string) *ChunkCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetTextHash sets the "text_hash" field.
func (_c *ChunkCreate) SetTextHash(v string) *ChunkCreate {
	_c.mutation.SetTextHash(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChunkCreate) SetMetadata(v map[string]interface{}) *ChunkCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetTokenCount sets the "token_count" field.
func (_c *ChunkCreate) SetTokenCount(v int) *ChunkCreate {
	_c.mutation.SetTokenCount(v)
	return _c
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableTokenCount(v *int) *ChunkCreate {
	if v != nil {
		_c.SetTokenCount(*v)
	}
	return _c
}

// SetQdrantPointID sets the "qdrant_point_id" field.
func (_c *ChunkCreate) SetQdrantPointID(v uuid.UUID) *ChunkCreate {
	_c.mutation.SetQdrantPointID(v)
	return _c
}

// SetNillableQdrantPointID sets the "qdrant_point_id" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableQdrantPointID(v *uuid.UUID) *ChunkCreate {
	if v != nil {
		_c.SetQdrantPointID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChunkCreate) SetID(v uuid.UUID) *ChunkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChunkCreate) SetNillableID(v *uuid.UUID) *ChunkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDocument sets the "document" edge to the Document entity.
func (_c *ChunkCreate) SetDocument(v *Document) *ChunkCreate {
	return _c.SetDocumentID(v.ID)
}

// Mutation returns the ChunkMutation object of the builder.
func (_c *ChunkCreate) Mutation() *ChunkMutation {
	return _c.mutation
}

// Save creates the Chunk in the database.
func (_c *ChunkCreate) Save(ctx context.Context) (*Chunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChunkCreate) SaveX(ctx context.Context) *Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChunkCreate) defaults() {
	if _, ok := _c.mutation.Metadata(); !ok {
		v := chunk.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := chunk.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChunkCreate) check() error {
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "Chunk.document_id"`)}
	}
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "Chunk.chunk_index"`)}
	}
	if _, ok := _c.mutation.ChunkType(); !ok {
		return &ValidationError{Name: "chunk_type", err: errors.New(`ent: missing required field "Chunk.chunk_type"`)}
	}
	if v, ok := _c.mutation.ChunkType(); ok {
		if err := chunk.ChunkTypeValidator(v); err != nil {
			return &ValidationError{Name: "chunk_type", err: fmt.Errorf(`ent: validator failed for field "Chunk.chunk_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Chunk.text"`)}
	}
	if v, ok := _c.mutation.Text(); ok {
		if err := chunk.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Chunk.text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TextHash(); !ok {
		return &ValidationError{Name: "text_hash", err: errors.New(`ent: missing required field "Chunk.text_hash"`)}
	}
	if v, ok := _c.mutation.TextHash(); ok {
		if err := chunk.TextHashValidator(v); err != nil {
			return &ValidationError{Name: "text_hash", err: fmt.Errorf(`ent: validator failed for field "Chunk.text_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Chunk.metadata"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "Chunk.document"`)}
	}
	return nil
}

func (_c *ChunkCreate) sqlSave(ctx context.Context) (*Chunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChunkCreate) createSpec() (*Chunk, *sqlgraph.CreateSpec) {
	var (
		_node = &Chunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chunk.Table, sqlgraph.NewFieldSpec(chunk.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChunkIndex(); ok {
		_spec.SetField(chunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := _c.mutation.ChunkType(); ok {
		_spec.SetField(chunk.FieldChunkType, field.TypeString, value)
		_node.ChunkType = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(chunk.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(chunk.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.TextHash(); ok {
		_spec.SetField(chunk.FieldTextHash, field.TypeString, value)
		_node.TextHash = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chunk.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.TokenCount(); ok {
		_spec.SetField(chunk.FieldTokenCount, field.TypeInt, value)
		_node.TokenCount = value
	}
	if value, ok := _c.mutation.QdrantPointID(); ok {
		_spec.SetField(chunk.FieldQdrantPointID, field.TypeUUID, value)
		_node.QdrantPointID = &value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chunk.DocumentTable,
			Columns: []string{chunk.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(document.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.Create().
//		SetDocumentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetDocumentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertOne {
	_c.conflict = opts
	return &ChunkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreate) OnConflictColumns(columns ...string) *ChunkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertOne{
		create: _c,
	}
}

type (
	// ChunkUpsertOne is the builder for "upsert"-ing
	//  one Chunk node.
	ChunkUpsertOne struct {
		create *ChunkCreate
	}

	// ChunkUpsert is the "OnConflict" setter.
	ChunkUpsert struct {
		*sql.UpdateSet
	}
)

// SetDocumentID sets the "document_id" field.
func (u *ChunkUpsert) SetDocumentID(v uuid.UUID) *ChunkUpsert {
	u.Set(chunk.FieldDocumentID, v)
	return u
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateDocumentID() *ChunkUpsert {
	u.SetExcluded(chunk.FieldDocumentID)
	return u
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsert) SetChunkIndex(v int) *ChunkUpsert {
	u.Set(chunk.FieldChunkIndex, v)
	return u
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateChunkIndex() *ChunkUpsert {
	u.SetExcluded(chunk.FieldChunkIndex)
	return u
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsert) AddChunkIndex(v int) *ChunkUpsert {
	u.Add(chunk.FieldChunkIndex, v)
	return u
}

// SetChunkType sets the "chunk_type" field.
func (u *ChunkUpsert) SetChunkType(v string) *ChunkUpsert {
	u.Set(chunk.FieldChunkType, v)
	return u
}

// UpdateChunkType sets the "chunk_type" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateChunkType() *ChunkUpsert {
	u.SetExcluded(chunk.FieldChunkType)
	return u
}

// SetTitle sets the "title" field.
func (u *ChunkUpsert) SetTitle(v string) *ChunkUpsert {
	u.Set(chunk.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateTitle() *ChunkUpsert {
	u.SetExcluded(chunk.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *ChunkUpsert) ClearTitle() *ChunkUpsert {
	u.SetNull(chunk.FieldTitle)
	return u
}

// SetText sets the "text" field.
func (u *ChunkUpsert) SetText(v string) *ChunkUpsert {
	u.Set(chunk.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateText() *ChunkUpsert {
	u.SetExcluded(chunk.FieldText)
	return u
}

// SetTextHash sets the "text_hash" field.
func (u *ChunkUpsert) SetTextHash(v string) *ChunkUpsert {
	u.Set(chunk.FieldTextHash, v)
	return u
}

// UpdateTextHash sets the "text_hash" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateTextHash() *ChunkUpsert {
	u.SetExcluded(chunk.FieldTextHash)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ChunkUpsert) SetMetadata(v map[string]interface{}) *ChunkUpsert {
	u.Set(chunk.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateMetadata() *ChunkUpsert {
	u.SetExcluded(chunk.FieldMetadata)
	return u
}

// SetTokenCount sets the "token_count" field.
func (u *ChunkUpsert) SetTokenCount(v int) *ChunkUpsert {
	u.Set(chunk.FieldTokenCount, v)
	return u
}

// UpdateTokenCount sets the "token_count" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateTokenCount() *ChunkUpsert {
	u.SetExcluded(chunk.FieldTokenCount)
	return u
}

// AddTokenCount adds v to the "token_count" field.
func (u *ChunkUpsert) AddTokenCount(v int) *ChunkUpsert {
	u.Add(chunk.FieldTokenCount, v)
	return u
}

// ClearTokenCount clears the value of the "token_count" field.
func (u *ChunkUpsert) ClearTokenCount() *ChunkUpsert {
	u.SetNull(chunk.FieldTokenCount)
	return u
}

// SetQdrantPointID sets the "qdrant_point_id" field.
func (u *ChunkUpsert) SetQdrantPointID(v uuid.UUID) *ChunkUpsert {
	u.Set(chunk.FieldQdrantPointID, v)
	return u
}

// UpdateQdrantPointID sets the "qdrant_point_id" field to the value that was provided on create.
func (u *ChunkUpsert) UpdateQdrantPointID() *ChunkUpsert {
	u.SetExcluded(chunk.FieldQdrantPointID)
	return u
}

// ClearQdrantPointID clears the value of the "qdrant_point_id" field.
func (u *ChunkUpsert) ClearQdrantPointID() *ChunkUpsert {
	u.SetNull(chunk.FieldQdrantPointID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chunk.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChunkUpsertOne) UpdateNewValues() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(chunk.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChunkUpsertOne) Ignore() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertOne) DoNothing() *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreate.OnConflict
// documentation for more info.
func (u *ChunkUpsertOne) Update(set func(*ChunkUpsert)) *ChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *ChunkUpsertOne) SetDocumentID(v uuid.UUID) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateDocumentID() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateDocumentID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsertOne) SetChunkIndex(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsertOne) AddChunkIndex(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateChunkIndex() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetChunkType sets the "chunk_type" field.
func (u *ChunkUpsertOne) SetChunkType(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkType(v)
	})
}

// UpdateChunkType sets the "chunk_type" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateChunkType() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkType()
	})
}

// SetTitle sets the "title" field.
func (u *ChunkUpsertOne) SetTitle(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateTitle() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *ChunkUpsertOne) ClearTitle() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTitle()
	})
}

// SetText sets the "text" field.
func (u *ChunkUpsertOne) SetText(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateText() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateText()
	})
}

// SetTextHash sets the "text_hash" field.
func (u *ChunkUpsertOne) SetTextHash(v string) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTextHash(v)
	})
}

// UpdateTextHash sets the "text_hash" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateTextHash() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTextHash()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChunkUpsertOne) SetMetadata(v map[string]interface{}) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateMetadata() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateMetadata()
	})
}

// SetTokenCount sets the "token_count" field.
func (u *ChunkUpsertOne) SetTokenCount(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTokenCount(v)
	})
}

// AddTokenCount adds v to the "token_count" field.
func (u *ChunkUpsertOne) AddTokenCount(v int) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.AddTokenCount(v)
	})
}

// UpdateTokenCount sets the "token_count" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateTokenCount() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTokenCount()
	})
}

// ClearTokenCount clears the value of the "token_count" field.
func (u *ChunkUpsertOne) ClearTokenCount() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTokenCount()
	})
}

// SetQdrantPointID sets the "qdrant_point_id" field.
func (u *ChunkUpsertOne) SetQdrantPointID(v uuid.UUID) *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.SetQdrantPointID(v)
	})
}

// UpdateQdrantPointID sets the "qdrant_point_id" field to the value that was provided on create.
func (u *ChunkUpsertOne) UpdateQdrantPointID() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateQdrantPointID()
	})
}

// ClearQdrantPointID clears the value of the "qdrant_point_id" field.
func (u *ChunkUpsertOne) ClearQdrantPointID() *ChunkUpsertOne {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearQdrantPointID()
	})
}

// Exec executes the query.
func (u *ChunkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChunkUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ChunkUpsertOne.ID is not supported by MySQL driver. Use ChunkUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChunkUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChunkCreateBulk is the builder for creating many Chunk entities in bulk.
type ChunkCreateBulk struct {
	config
	err      error
	builders []*ChunkCreate
	conflict []sql.ConflictOption
}

// Save creates the Chunk entities in the database.
func (_c *ChunkCreateBulk) Save(ctx context.Context) ([]*Chunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChunkCreateBulk) SaveX(ctx context.Context) []*Chunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Chunk.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChunkUpsert) {
//			SetDocumentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChunkUpsertBulk {
	_c.conflict = opts
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChunkCreateBulk) OnConflictColumns(columns ...string) *ChunkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChunkUpsertBulk{
		create: _c,
	}
}

// ChunkUpsertBulk is the builder for "upsert"-ing
// a bulk of Chunk nodes.
type ChunkUpsertBulk struct {
	create *ChunkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(chunk.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ChunkUpsertBulk) UpdateNewValues() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(chunk.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Chunk.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChunkUpsertBulk) Ignore() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChunkUpsertBulk) DoNothing() *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChunkCreateBulk.OnConflict
// documentation for more info.
func (u *ChunkUpsertBulk) Update(set func(*ChunkUpsert)) *ChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *ChunkUpsertBulk) SetDocumentID(v uuid.UUID) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateDocumentID() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateDocumentID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *ChunkUpsertBulk) SetChunkIndex(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *ChunkUpsertBulk) AddChunkIndex(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateChunkIndex() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetChunkType sets the "chunk_type" field.
func (u *ChunkUpsertBulk) SetChunkType(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetChunkType(v)
	})
}

// UpdateChunkType sets the "chunk_type" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateChunkType() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateChunkType()
	})
}

// SetTitle sets the "title" field.
func (u *ChunkUpsertBulk) SetTitle(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateTitle() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *ChunkUpsertBulk) ClearTitle() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTitle()
	})
}

// SetText sets the "text" field.
func (u *ChunkUpsertBulk) SetText(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateText() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateText()
	})
}

// SetTextHash sets the "text_hash" field.
func (u *ChunkUpsertBulk) SetTextHash(v string) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTextHash(v)
	})
}

// UpdateTextHash sets the "text_hash" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateTextHash() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTextHash()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChunkUpsertBulk) SetMetadata(v map[string]interface{}) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateMetadata() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateMetadata()
	})
}

// SetTokenCount sets the "token_count" field.
func (u *ChunkUpsertBulk) SetTokenCount(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetTokenCount(v)
	})
}

// AddTokenCount adds v to the "token_count" field.
func (u *ChunkUpsertBulk) AddTokenCount(v int) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.AddTokenCount(v)
	})
}

// UpdateTokenCount sets the "token_count" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateTokenCount() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateTokenCount()
	})
}

// ClearTokenCount clears the value of the "token_count" field.
func (u *ChunkUpsertBulk) ClearTokenCount() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearTokenCount()
	})
}

// SetQdrantPointID sets the "qdrant_point_id" field.
func (u *ChunkUpsertBulk) SetQdrantPointID(v uuid.UUID) *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.SetQdrantPointID(v)
	})
}

// UpdateQdrantPointID sets the "qdrant_point_id" field to the value that was provided on create.
func (u *ChunkUpsertBulk) UpdateQdrantPointID() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.UpdateQdrantPointID()
	})
}

// ClearQdrantPointID clears the value of the "qdrant_point_id" field.
func (u *ChunkUpsertBulk) ClearQdrantPointID() *ChunkUpsertBulk {
	return u.Update(func(s *ChunkUpsert) {
		s.ClearQdrantPointID()
	})
}

// Exec executes the query.
func (u *ChunkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChunkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChunkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChunkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
