// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-faster/sisyphus/internal/ent/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/go-faster/sisyphus/internal/ent/chunk"
	"github.com/go-faster/sisyphus/internal/ent/document"
	"github.com/go-faster/sisyphus/internal/ent/supportrequest"
	"github.com/go-faster/sisyphus/internal/ent/syncstate"
	"github.com/go-faster/sisyphus/internal/ent/telegrammessage"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Chunk is the client for interacting with the Chunk builders.
	Chunk *ChunkClient
	// Document is the client for interacting with the Document builders.
	Document *DocumentClient
	// SupportRequest is the client for interacting with the SupportRequest builders.
	SupportRequest *SupportRequestClient
	// SyncState is the client for interacting with the SyncState builders.
	SyncState *SyncStateClient
	// TelegramMessage is the client for interacting with the TelegramMessage builders.
	TelegramMessage *TelegramMessageClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Chunk = NewChunkClient(c.config)
	c.Document = NewDocumentClient(c.config)
	c.SupportRequest = NewSupportRequestClient(c.config)
	c.SyncState = NewSyncStateClient(c.config)
	c.TelegramMessage = NewTelegramMessageClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Chunk:           NewChunkClient(cfg),
		Document:        NewDocumentClient(cfg),
		SupportRequest:  NewSupportRequestClient(cfg),
		SyncState:       NewSyncStateClient(cfg),
		TelegramMessage: NewTelegramMessageClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Chunk:           NewChunkClient(cfg),
		Document:        NewDocumentClient(cfg),
		SupportRequest:  NewSupportRequestClient(cfg),
		SyncState:       NewSyncStateClient(cfg),
		TelegramMessage: NewTelegramMessageClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Chunk.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Chunk.Use(hooks...)
	c.Document.Use(hooks...)
	c.SupportRequest.Use(hooks...)
	c.SyncState.Use(hooks...)
	c.TelegramMessage.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Chunk.Intercept(interceptors...)
	c.Document.Intercept(interceptors...)
	c.SupportRequest.Intercept(interceptors...)
	c.SyncState.Intercept(interceptors...)
	c.TelegramMessage.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ChunkMutation:
		return c.Chunk.mutate(ctx, m)
	case *DocumentMutation:
		return c.Document.mutate(ctx, m)
	case *SupportRequestMutation:
		return c.SupportRequest.mutate(ctx, m)
	case *SyncStateMutation:
		return c.SyncState.mutate(ctx, m)
	case *TelegramMessageMutation:
		return c.TelegramMessage.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ChunkClient is a client for the Chunk schema.
type ChunkClient struct {
	config
}

// NewChunkClient returns a client for the Chunk from the given config.
func NewChunkClient(c config) *ChunkClient {
	return &ChunkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `chunk.Hooks(f(g(h())))`.
func (c *ChunkClient) Use(hooks ...Hook) {
	c.hooks.Chunk = append(c.hooks.Chunk, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `chunk.Intercept(f(g(h())))`.
func (c *ChunkClient) Intercept(interceptors ...Interceptor) {
	c.inters.Chunk = append(c.inters.Chunk, interceptors...)
}

// Create returns a builder for creating a Chunk entity.
func (c *ChunkClient) Create() *ChunkCreate {
	mutation := newChunkMutation(c.config, OpCreate)
	return &ChunkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Chunk entities.
func (c *ChunkClient) CreateBulk(builders ...*ChunkCreate) *ChunkCreateBulk {
	return &ChunkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ChunkClient) MapCreateBulk(slice any, setFunc func(*ChunkCreate, int)) *ChunkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ChunkCreateBulk{err: fmt.Errorf("calling to ChunkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ChunkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ChunkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Chunk.
func (c *ChunkClient) Update() *ChunkUpdate {
	mutation := newChunkMutation(c.config, OpUpdate)
	return &ChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ChunkClient) UpdateOne(_m *Chunk) *ChunkUpdateOne {
	mutation := newChunkMutation(c.config, OpUpdateOne, withChunk(_m))
	return &ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ChunkClient) UpdateOneID(id uuid.UUID) *ChunkUpdateOne {
	mutation := newChunkMutation(c.config, OpUpdateOne, withChunkID(id))
	return &ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Chunk.
func (c *ChunkClient) Delete() *ChunkDelete {
	mutation := newChunkMutation(c.config, OpDelete)
	return &ChunkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ChunkClient) DeleteOne(_m *Chunk) *ChunkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ChunkClient) DeleteOneID(id uuid.UUID) *ChunkDeleteOne {
	builder := c.Delete().Where(chunk.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ChunkDeleteOne{builder}
}

// Query returns a query builder for Chunk.
func (c *ChunkClient) Query() *ChunkQuery {
	return &ChunkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeChunk},
		inters: c.Interceptors(),
	}
}

// Get returns a Chunk entity by its id.
func (c *ChunkClient) Get(ctx context.Context, id uuid.UUID) (*Chunk, error) {
	return c.Query().Where(chunk.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ChunkClient) GetX(ctx context.Context, id uuid.UUID) *Chunk {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDocument queries the document edge of a Chunk.
func (c *ChunkClient) QueryDocument(_m *Chunk) *DocumentQuery {
	query := (&DocumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(chunk.Table, chunk.FieldID, id),
			sqlgraph.To(document.Table, document.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chunk.DocumentTable, chunk.DocumentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ChunkClient) Hooks() []Hook {
	return c.hooks.Chunk
}

// Interceptors returns the client interceptors.
func (c *ChunkClient) Interceptors() []Interceptor {
	return c.inters.Chunk
}

func (c *ChunkClient) mutate(ctx context.Context, m *ChunkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ChunkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ChunkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ChunkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ChunkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Chunk mutation op: %q", m.Op())
	}
}

// DocumentClient is a client for the Document schema.
type DocumentClient struct {
	config
}

// NewDocumentClient returns a client for the Document from the given config.
func NewDocumentClient(c config) *DocumentClient {
	return &DocumentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `document.Hooks(f(g(h())))`.
func (c *DocumentClient) Use(hooks ...Hook) {
	c.hooks.Document = append(c.hooks.Document, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `document.Intercept(f(g(h())))`.
func (c *DocumentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Document = append(c.inters.Document, interceptors...)
}

// Create returns a builder for creating a Document entity.
func (c *DocumentClient) Create() *DocumentCreate {
	mutation := newDocumentMutation(c.config, OpCreate)
	return &DocumentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Document entities.
func (c *DocumentClient) CreateBulk(builders ...*DocumentCreate) *DocumentCreateBulk {
	return &DocumentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DocumentClient) MapCreateBulk(slice any, setFunc func(*DocumentCreate, int)) *DocumentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DocumentCreateBulk{err: fmt.Errorf("calling to DocumentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DocumentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DocumentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Document.
func (c *DocumentClient) Update() *DocumentUpdate {
	mutation := newDocumentMutation(c.config, OpUpdate)
	return &DocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DocumentClient) UpdateOne(_m *Document) *DocumentUpdateOne {
	mutation := newDocumentMutation(c.config, OpUpdateOne, withDocument(_m))
	return &DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DocumentClient) UpdateOneID(id uuid.UUID) *DocumentUpdateOne {
	mutation := newDocumentMutation(c.config, OpUpdateOne, withDocumentID(id))
	return &DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Document.
func (c *DocumentClient) Delete() *DocumentDelete {
	mutation := newDocumentMutation(c.config, OpDelete)
	return &DocumentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DocumentClient) DeleteOne(_m *Document) *DocumentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DocumentClient) DeleteOneID(id uuid.UUID) *DocumentDeleteOne {
	builder := c.Delete().Where(document.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DocumentDeleteOne{builder}
}

// Query returns a query builder for Document.
func (c *DocumentClient) Query() *DocumentQuery {
	return &DocumentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDocument},
		inters: c.Interceptors(),
	}
}

// Get returns a Document entity by its id.
func (c *DocumentClient) Get(ctx context.Context, id uuid.UUID) (*Document, error) {
	return c.Query().Where(document.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DocumentClient) GetX(ctx context.Context, id uuid.UUID) *Document {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryChunks queries the chunks edge of a Document.
func (c *DocumentClient) QueryChunks(_m *Document) *ChunkQuery {
	query := (&ChunkClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(document.Table, document.FieldID, id),
			sqlgraph.To(chunk.Table, chunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, document.ChunksTable, document.ChunksColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DocumentClient) Hooks() []Hook {
	return c.hooks.Document
}

// Interceptors returns the client interceptors.
func (c *DocumentClient) Interceptors() []Interceptor {
	return c.inters.Document
}

func (c *DocumentClient) mutate(ctx context.Context, m *DocumentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DocumentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DocumentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Document mutation op: %q", m.Op())
	}
}

// SupportRequestClient is a client for the SupportRequest schema.
type SupportRequestClient struct {
	config
}

// NewSupportRequestClient returns a client for the SupportRequest from the given config.
func NewSupportRequestClient(c config) *SupportRequestClient {
	return &SupportRequestClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `supportrequest.Hooks(f(g(h())))`.
func (c *SupportRequestClient) Use(hooks ...Hook) {
	c.hooks.SupportRequest = append(c.hooks.SupportRequest, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `supportrequest.Intercept(f(g(h())))`.
func (c *SupportRequestClient) Intercept(interceptors ...Interceptor) {
	c.inters.SupportRequest = append(c.inters.SupportRequest, interceptors...)
}

// Create returns a builder for creating a SupportRequest entity.
func (c *SupportRequestClient) Create() *SupportRequestCreate {
	mutation := newSupportRequestMutation(c.config, OpCreate)
	return &SupportRequestCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SupportRequest entities.
func (c *SupportRequestClient) CreateBulk(builders ...*SupportRequestCreate) *SupportRequestCreateBulk {
	return &SupportRequestCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SupportRequestClient) MapCreateBulk(slice any, setFunc func(*SupportRequestCreate, int)) *SupportRequestCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SupportRequestCreateBulk{err: fmt.Errorf("calling to SupportRequestClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SupportRequestCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SupportRequestCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SupportRequest.
func (c *SupportRequestClient) Update() *SupportRequestUpdate {
	mutation := newSupportRequestMutation(c.config, OpUpdate)
	return &SupportRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SupportRequestClient) UpdateOne(_m *SupportRequest) *SupportRequestUpdateOne {
	mutation := newSupportRequestMutation(c.config, OpUpdateOne, withSupportRequest(_m))
	return &SupportRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SupportRequestClient) UpdateOneID(id uuid.UUID) *SupportRequestUpdateOne {
	mutation := newSupportRequestMutation(c.config, OpUpdateOne, withSupportRequestID(id))
	return &SupportRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SupportRequest.
func (c *SupportRequestClient) Delete() *SupportRequestDelete {
	mutation := newSupportRequestMutation(c.config, OpDelete)
	return &SupportRequestDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SupportRequestClient) DeleteOne(_m *SupportRequest) *SupportRequestDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SupportRequestClient) DeleteOneID(id uuid.UUID) *SupportRequestDeleteOne {
	builder := c.Delete().Where(supportrequest.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SupportRequestDeleteOne{builder}
}

// Query returns a query builder for SupportRequest.
func (c *SupportRequestClient) Query() *SupportRequestQuery {
	return &SupportRequestQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSupportRequest},
		inters: c.Interceptors(),
	}
}

// Get returns a SupportRequest entity by its id.
func (c *SupportRequestClient) Get(ctx context.Context, id uuid.UUID) (*SupportRequest, error) {
	return c.Query().Where(supportrequest.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SupportRequestClient) GetX(ctx context.Context, id uuid.UUID) *SupportRequest {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SupportRequestClient) Hooks() []Hook {
	return c.hooks.SupportRequest
}

// Interceptors returns the client interceptors.
func (c *SupportRequestClient) Interceptors() []Interceptor {
	return c.inters.SupportRequest
}

func (c *SupportRequestClient) mutate(ctx context.Context, m *SupportRequestMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SupportRequestCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SupportRequestUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SupportRequestUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SupportRequestDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SupportRequest mutation op: %q", m.Op())
	}
}

// SyncStateClient is a client for the SyncState schema.
type SyncStateClient struct {
	config
}

// NewSyncStateClient returns a client for the SyncState from the given config.
func NewSyncStateClient(c config) *SyncStateClient {
	return &SyncStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncstate.Hooks(f(g(h())))`.
func (c *SyncStateClient) Use(hooks ...Hook) {
	c.hooks.SyncState = append(c.hooks.SyncState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncstate.Intercept(f(g(h())))`.
func (c *SyncStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncState = append(c.inters.SyncState, interceptors...)
}

// Create returns a builder for creating a SyncState entity.
func (c *SyncStateClient) Create() *SyncStateCreate {
	mutation := newSyncStateMutation(c.config, OpCreate)
	return &SyncStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncState entities.
func (c *SyncStateClient) CreateBulk(builders ...*SyncStateCreate) *SyncStateCreateBulk {
	return &SyncStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncStateClient) MapCreateBulk(slice any, setFunc func(*SyncStateCreate, int)) *SyncStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncStateCreateBulk{err: fmt.Errorf("calling to SyncStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncState.
func (c *SyncStateClient) Update() *SyncStateUpdate {
	mutation := newSyncStateMutation(c.config, OpUpdate)
	return &SyncStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncStateClient) UpdateOne(_m *SyncState) *SyncStateUpdateOne {
	mutation := newSyncStateMutation(c.config, OpUpdateOne, withSyncState(_m))
	return &SyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncStateClient) UpdateOneID(id uuid.UUID) *SyncStateUpdateOne {
	mutation := newSyncStateMutation(c.config, OpUpdateOne, withSyncStateID(id))
	return &SyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncState.
func (c *SyncStateClient) Delete() *SyncStateDelete {
	mutation := newSyncStateMutation(c.config, OpDelete)
	return &SyncStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncStateClient) DeleteOne(_m *SyncState) *SyncStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncStateClient) DeleteOneID(id uuid.UUID) *SyncStateDeleteOne {
	builder := c.Delete().Where(syncstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncStateDeleteOne{builder}
}

// Query returns a query builder for SyncState.
func (c *SyncStateClient) Query() *SyncStateQuery {
	return &SyncStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncState},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncState entity by its id.
func (c *SyncStateClient) Get(ctx context.Context, id uuid.UUID) (*SyncState, error) {
	return c.Query().Where(syncstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncStateClient) GetX(ctx context.Context, id uuid.UUID) *SyncState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncStateClient) Hooks() []Hook {
	return c.hooks.SyncState
}

// Interceptors returns the client interceptors.
func (c *SyncStateClient) Interceptors() []Interceptor {
	return c.inters.SyncState
}

func (c *SyncStateClient) mutate(ctx context.Context, m *SyncStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncState mutation op: %q", m.Op())
	}
}

// TelegramMessageClient is a client for the TelegramMessage schema.
type TelegramMessageClient struct {
	config
}

// NewTelegramMessageClient returns a client for the TelegramMessage from the given config.
func NewTelegramMessageClient(c config) *TelegramMessageClient {
	return &TelegramMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `telegrammessage.Hooks(f(g(h())))`.
func (c *TelegramMessageClient) Use(hooks ...Hook) {
	c.hooks.TelegramMessage = append(c.hooks.TelegramMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `telegrammessage.Intercept(f(g(h())))`.
func (c *TelegramMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.TelegramMessage = append(c.inters.TelegramMessage, interceptors...)
}

// Create returns a builder for creating a TelegramMessage entity.
func (c *TelegramMessageClient) Create() *TelegramMessageCreate {
	mutation := newTelegramMessageMutation(c.config, OpCreate)
	return &TelegramMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TelegramMessage entities.
func (c *TelegramMessageClient) CreateBulk(builders ...*TelegramMessageCreate) *TelegramMessageCreateBulk {
	return &TelegramMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TelegramMessageClient) MapCreateBulk(slice any, setFunc func(*TelegramMessageCreate, int)) *TelegramMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TelegramMessageCreateBulk{err: fmt.Errorf("calling to TelegramMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TelegramMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TelegramMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TelegramMessage.
func (c *TelegramMessageClient) Update() *TelegramMessageUpdate {
	mutation := newTelegramMessageMutation(c.config, OpUpdate)
	return &TelegramMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TelegramMessageClient) UpdateOne(_m *TelegramMessage) *TelegramMessageUpdateOne {
	mutation := newTelegramMessageMutation(c.config, OpUpdateOne, withTelegramMessage(_m))
	return &TelegramMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TelegramMessageClient) UpdateOneID(id uuid.UUID) *TelegramMessageUpdateOne {
	mutation := newTelegramMessageMutation(c.config, OpUpdateOne, withTelegramMessageID(id))
	return &TelegramMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TelegramMessage.
func (c *TelegramMessageClient) Delete() *TelegramMessageDelete {
	mutation := newTelegramMessageMutation(c.config, OpDelete)
	return &TelegramMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TelegramMessageClient) DeleteOne(_m *TelegramMessage) *TelegramMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TelegramMessageClient) DeleteOneID(id uuid.UUID) *TelegramMessageDeleteOne {
	builder := c.Delete().Where(telegrammessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TelegramMessageDeleteOne{builder}
}

// Query returns a query builder for TelegramMessage.
func (c *TelegramMessageClient) Query() *TelegramMessageQuery {
	return &TelegramMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTelegramMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a TelegramMessage entity by its id.
func (c *TelegramMessageClient) Get(ctx context.Context, id uuid.UUID) (*TelegramMessage, error) {
	return c.Query().Where(telegrammessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TelegramMessageClient) GetX(ctx context.Context, id uuid.UUID) *TelegramMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TelegramMessageClient) Hooks() []Hook {
	return c.hooks.TelegramMessage
}

// Interceptors returns the client interceptors.
func (c *TelegramMessageClient) Interceptors() []Interceptor {
	return c.inters.TelegramMessage
}

func (c *TelegramMessageClient) mutate(ctx context.Context, m *TelegramMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TelegramMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TelegramMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TelegramMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TelegramMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TelegramMessage mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Chunk, Document, SupportRequest, SyncState, TelegramMessage []ent.Hook
	}
	inters struct {
		Chunk, Document, SupportRequest, SyncState, TelegramMessage []ent.Interceptor
	}
)
