// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/sisyphus/internal/ent/notifysubscription"
	"github.com/go-faster/sisyphus/internal/ent/predicate"
	"github.com/go-faster/sisyphus/internal/ent/user"
	"github.com/google/uuid"
)

// NotifySubscriptionUpdate is the builder for updating NotifySubscription entities.
type NotifySubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *NotifySubscriptionMutation
}

// Where appends a list predicates to the NotifySubscriptionUpdate builder.
func (_u *NotifySubscriptionUpdate) Where(ps ...predicate.NotifySubscription) *NotifySubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotifySubscriptionUpdate) SetUserID(v uuid.UUID) *NotifySubscriptionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableUserID(v *uuid.UUID) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *NotifySubscriptionUpdate) SetSource(v string) *NotifySubscriptionUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableSource(v *string) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *NotifySubscriptionUpdate) SetEventTypes(v []string) *NotifySubscriptionUpdate {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *NotifySubscriptionUpdate) AppendEventTypes(v []string) *NotifySubscriptionUpdate {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// SetFilters sets the "filters" field.
func (_u *NotifySubscriptionUpdate) SetFilters(v map[string]interface{}) *NotifySubscriptionUpdate {
	_u.mutation.SetFilters(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifySubscriptionUpdate) SetEnabled(v bool) *NotifySubscriptionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifySubscriptionUpdate) SetNillableEnabled(v *bool) *NotifySubscriptionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifySubscriptionUpdate) SetUpdatedAt(v time.Time) *NotifySubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotifySubscriptionUpdate) SetUser(v *User) *NotifySubscriptionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotifySubscriptionMutation object of the builder.
func (_u *NotifySubscriptionUpdate) Mutation() *NotifySubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotifySubscriptionUpdate) ClearUser() *NotifySubscriptionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifySubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifySubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifySubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifySubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifySubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notifysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifySubscriptionUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := notifysubscription.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "NotifySubscription.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotifySubscription.user"`)
	}
	return nil
}

func (_u *NotifySubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifysubscription.Table, notifysubscription.Columns, sqlgraph.NewFieldSpec(notifysubscription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(notifysubscription.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(notifysubscription.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifysubscription.FieldEventTypes, value)
		})
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(notifysubscription.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.UserTable,
			Columns: []string{notifysubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.UserTable,
			Columns: []string{notifysubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifySubscriptionUpdateOne is the builder for updating a single NotifySubscription entity.
type NotifySubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotifySubscriptionMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotifySubscriptionUpdateOne) SetUserID(v uuid.UUID) *NotifySubscriptionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableUserID(v *uuid.UUID) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *NotifySubscriptionUpdateOne) SetSource(v string) *NotifySubscriptionUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableSource(v *string) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetEventTypes sets the "event_types" field.
func (_u *NotifySubscriptionUpdateOne) SetEventTypes(v []string) *NotifySubscriptionUpdateOne {
	_u.mutation.SetEventTypes(v)
	return _u
}

// AppendEventTypes appends value to the "event_types" field.
func (_u *NotifySubscriptionUpdateOne) AppendEventTypes(v []string) *NotifySubscriptionUpdateOne {
	_u.mutation.AppendEventTypes(v)
	return _u
}

// SetFilters sets the "filters" field.
func (_u *NotifySubscriptionUpdateOne) SetFilters(v map[string]interface{}) *NotifySubscriptionUpdateOne {
	_u.mutation.SetFilters(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifySubscriptionUpdateOne) SetEnabled(v bool) *NotifySubscriptionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifySubscriptionUpdateOne) SetNillableEnabled(v *bool) *NotifySubscriptionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifySubscriptionUpdateOne) SetUpdatedAt(v time.Time) *NotifySubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotifySubscriptionUpdateOne) SetUser(v *User) *NotifySubscriptionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotifySubscriptionMutation object of the builder.
func (_u *NotifySubscriptionUpdateOne) Mutation() *NotifySubscriptionMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotifySubscriptionUpdateOne) ClearUser() *NotifySubscriptionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the NotifySubscriptionUpdate builder.
func (_u *NotifySubscriptionUpdateOne) Where(ps ...predicate.NotifySubscription) *NotifySubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifySubscriptionUpdateOne) Select(field string, fields ...string) *NotifySubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifySubscription entity.
func (_u *NotifySubscriptionUpdateOne) Save(ctx context.Context) (*NotifySubscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifySubscriptionUpdateOne) SaveX(ctx context.Context) *NotifySubscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifySubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifySubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifySubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notifysubscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifySubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := notifysubscription.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "NotifySubscription.source": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotifySubscription.user"`)
	}
	return nil
}

func (_u *NotifySubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *NotifySubscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifysubscription.Table, notifysubscription.Columns, sqlgraph.NewFieldSpec(notifysubscription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotifySubscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifysubscription.FieldID)
		for _, f := range fields {
			if !notifysubscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notifysubscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(notifysubscription.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventTypes(); ok {
		_spec.SetField(notifysubscription.FieldEventTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEventTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifysubscription.FieldEventTypes, value)
		})
	}
	if value, ok := _u.mutation.Filters(); ok {
		_spec.SetField(notifysubscription.FieldFilters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifysubscription.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifysubscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.UserTable,
			Columns: []string{notifysubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notifysubscription.UserTable,
			Columns: []string{notifysubscription.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotifySubscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifysubscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
