// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/sisyphus/internal/ent/predicate"
	"github.com/go-faster/sisyphus/internal/ent/queuejob"
)

// QueueJobUpdate is the builder for updating QueueJob entities.
type QueueJobUpdate struct {
	config
	hooks    []Hook
	mutation *QueueJobMutation
}

// Where appends a list predicates to the QueueJobUpdate builder.
func (_u *QueueJobUpdate) Where(ps ...predicate.QueueJob) *QueueJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPayload sets the "payload" field.
func (_u *QueueJobUpdate) SetPayload(v []byte) *QueueJobUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *QueueJobUpdate) ClearPayload() *QueueJobUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QueueJobUpdate) SetStatus(v string) *QueueJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableStatus(v *string) *QueueJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *QueueJobUpdate) SetAttempts(v int) *QueueJobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableAttempts(v *int) *QueueJobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *QueueJobUpdate) AddAttempts(v int) *QueueJobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *QueueJobUpdate) SetMaxAttempts(v int) *QueueJobUpdate {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableMaxAttempts(v *int) *QueueJobUpdate {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *QueueJobUpdate) AddMaxAttempts(v int) *QueueJobUpdate {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetVisibleAt sets the "visible_at" field.
func (_u *QueueJobUpdate) SetVisibleAt(v time.Time) *QueueJobUpdate {
	_u.mutation.SetVisibleAt(v)
	return _u
}

// SetNillableVisibleAt sets the "visible_at" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableVisibleAt(v *time.Time) *QueueJobUpdate {
	if v != nil {
		_u.SetVisibleAt(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *QueueJobUpdate) SetLeaseOwner(v string) *QueueJobUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableLeaseOwner(v *string) *QueueJobUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *QueueJobUpdate) ClearLeaseOwner() *QueueJobUpdate {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetError sets the "error" field.
func (_u *QueueJobUpdate) SetError(v string) *QueueJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableError(v *string) *QueueJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *QueueJobUpdate) ClearError() *QueueJobUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QueueJobUpdate) SetUpdatedAt(v time.Time) *QueueJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QueueJobUpdate) SetCompletedAt(v time.Time) *QueueJobUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QueueJobUpdate) SetNillableCompletedAt(v *time.Time) *QueueJobUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QueueJobUpdate) ClearCompletedAt() *QueueJobUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the QueueJobMutation object of the builder.
func (_u *QueueJobUpdate) Mutation() *QueueJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QueueJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QueueJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QueueJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QueueJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QueueJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := queuejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QueueJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(queuejob.Table, queuejob.Columns, sqlgraph.NewFieldSpec(queuejob.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(queuejob.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(queuejob.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(queuejob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(queuejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(queuejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(queuejob.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(queuejob.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VisibleAt(); ok {
		_spec.SetField(queuejob.FieldVisibleAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(queuejob.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(queuejob.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(queuejob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(queuejob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(queuejob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(queuejob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(queuejob.FieldCompletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{queuejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QueueJobUpdateOne is the builder for updating a single QueueJob entity.
type QueueJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QueueJobMutation
}

// SetPayload sets the "payload" field.
func (_u *QueueJobUpdateOne) SetPayload(v []byte) *QueueJobUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *QueueJobUpdateOne) ClearPayload() *QueueJobUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetStatus sets the "status" field.
func (_u *QueueJobUpdateOne) SetStatus(v string) *QueueJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableStatus(v *string) *QueueJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *QueueJobUpdateOne) SetAttempts(v int) *QueueJobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableAttempts(v *int) *QueueJobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *QueueJobUpdateOne) AddAttempts(v int) *QueueJobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetMaxAttempts sets the "max_attempts" field.
func (_u *QueueJobUpdateOne) SetMaxAttempts(v int) *QueueJobUpdateOne {
	_u.mutation.ResetMaxAttempts()
	_u.mutation.SetMaxAttempts(v)
	return _u
}

// SetNillableMaxAttempts sets the "max_attempts" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableMaxAttempts(v *int) *QueueJobUpdateOne {
	if v != nil {
		_u.SetMaxAttempts(*v)
	}
	return _u
}

// AddMaxAttempts adds value to the "max_attempts" field.
func (_u *QueueJobUpdateOne) AddMaxAttempts(v int) *QueueJobUpdateOne {
	_u.mutation.AddMaxAttempts(v)
	return _u
}

// SetVisibleAt sets the "visible_at" field.
func (_u *QueueJobUpdateOne) SetVisibleAt(v time.Time) *QueueJobUpdateOne {
	_u.mutation.SetVisibleAt(v)
	return _u
}

// SetNillableVisibleAt sets the "visible_at" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableVisibleAt(v *time.Time) *QueueJobUpdateOne {
	if v != nil {
		_u.SetVisibleAt(*v)
	}
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *QueueJobUpdateOne) SetLeaseOwner(v string) *QueueJobUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableLeaseOwner(v *string) *QueueJobUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// ClearLeaseOwner clears the value of the "lease_owner" field.
func (_u *QueueJobUpdateOne) ClearLeaseOwner() *QueueJobUpdateOne {
	_u.mutation.ClearLeaseOwner()
	return _u
}

// SetError sets the "error" field.
func (_u *QueueJobUpdateOne) SetError(v string) *QueueJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableError(v *string) *QueueJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *QueueJobUpdateOne) ClearError() *QueueJobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QueueJobUpdateOne) SetUpdatedAt(v time.Time) *QueueJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QueueJobUpdateOne) SetCompletedAt(v time.Time) *QueueJobUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QueueJobUpdateOne) SetNillableCompletedAt(v *time.Time) *QueueJobUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QueueJobUpdateOne) ClearCompletedAt() *QueueJobUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// Mutation returns the QueueJobMutation object of the builder.
func (_u *QueueJobUpdateOne) Mutation() *QueueJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the QueueJobUpdate builder.
func (_u *QueueJobUpdateOne) Where(ps ...predicate.QueueJob) *QueueJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QueueJobUpdateOne) Select(field string, fields ...string) *QueueJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QueueJob entity.
func (_u *QueueJobUpdateOne) Save(ctx context.Context) (*QueueJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QueueJobUpdateOne) SaveX(ctx context.Context) *QueueJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QueueJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QueueJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QueueJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := queuejob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QueueJobUpdateOne) sqlSave(ctx context.Context) (_node *QueueJob, err error) {
	_spec := sqlgraph.NewUpdateSpec(queuejob.Table, queuejob.Columns, sqlgraph.NewFieldSpec(queuejob.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QueueJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, queuejob.FieldID)
		for _, f := range fields {
			if !queuejob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != queuejob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(queuejob.FieldPayload, field.TypeBytes, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(queuejob.FieldPayload, field.TypeBytes)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(queuejob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(queuejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(queuejob.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxAttempts(); ok {
		_spec.SetField(queuejob.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAttempts(); ok {
		_spec.AddField(queuejob.FieldMaxAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VisibleAt(); ok {
		_spec.SetField(queuejob.FieldVisibleAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(queuejob.FieldLeaseOwner, field.TypeString, value)
	}
	if _u.mutation.LeaseOwnerCleared() {
		_spec.ClearField(queuejob.FieldLeaseOwner, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(queuejob.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(queuejob.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(queuejob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(queuejob.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(queuejob.FieldCompletedAt, field.TypeTime)
	}
	_node = &QueueJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{queuejob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
