// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/go-faster/sisyphus/internal/ent/chunk"
	"github.com/go-faster/sisyphus/internal/ent/document"
	"github.com/go-faster/sisyphus/internal/ent/investigationjob"
	"github.com/go-faster/sisyphus/internal/ent/notification"
	"github.com/go-faster/sisyphus/internal/ent/notifysubscription"
	"github.com/go-faster/sisyphus/internal/ent/schema"
	"github.com/go-faster/sisyphus/internal/ent/supportrequest"
	"github.com/go-faster/sisyphus/internal/ent/syncstate"
	"github.com/go-faster/sisyphus/internal/ent/telegrammessage"
	"github.com/go-faster/sisyphus/internal/ent/user"
	"github.com/go-faster/sisyphus/internal/ent/usertoken"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescChunkType is the schema descriptor for chunk_type field.
	chunkDescChunkType := chunkFields[3].Descriptor()
	// chunk.ChunkTypeValidator is a validator for the "chunk_type" field. It is called by the builders before save.
	chunk.ChunkTypeValidator = chunkDescChunkType.Validators[0].(func(string) error)
	// chunkDescText is the schema descriptor for text field.
	chunkDescText := chunkFields[5].Descriptor()
	// chunk.TextValidator is a validator for the "text" field. It is called by the builders before save.
	chunk.TextValidator = chunkDescText.Validators[0].(func(string) error)
	// chunkDescTextHash is the schema descriptor for text_hash field.
	chunkDescTextHash := chunkFields[6].Descriptor()
	// chunk.TextHashValidator is a validator for the "text_hash" field. It is called by the builders before save.
	chunk.TextHashValidator = chunkDescTextHash.Validators[0].(func(string) error)
	// chunkDescMetadata is the schema descriptor for metadata field.
	chunkDescMetadata := chunkFields[7].Descriptor()
	// chunk.DefaultMetadata holds the default value on creation for the metadata field.
	chunk.DefaultMetadata = chunkDescMetadata.Default.(map[string]interface{})
	// chunkDescID is the schema descriptor for id field.
	chunkDescID := chunkFields[0].Descriptor()
	// chunk.DefaultID holds the default value on creation for the id field.
	chunk.DefaultID = chunkDescID.Default.(func() uuid.UUID)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescSource is the schema descriptor for source field.
	documentDescSource := documentFields[1].Descriptor()
	// document.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	document.SourceValidator = documentDescSource.Validators[0].(func(string) error)
	// documentDescSourceID is the schema descriptor for source_id field.
	documentDescSourceID := documentFields[2].Descriptor()
	// document.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	document.SourceIDValidator = documentDescSourceID.Validators[0].(func(string) error)
	// documentDescBodyHash is the schema descriptor for body_hash field.
	documentDescBodyHash := documentFields[6].Descriptor()
	// document.BodyHashValidator is a validator for the "body_hash" field. It is called by the builders before save.
	document.BodyHashValidator = documentDescBodyHash.Validators[0].(func(string) error)
	// documentDescMetadata is the schema descriptor for metadata field.
	documentDescMetadata := documentFields[7].Descriptor()
	// document.DefaultMetadata holds the default value on creation for the metadata field.
	document.DefaultMetadata = documentDescMetadata.Default.(map[string]interface{})
	// documentDescChunkerVersion is the schema descriptor for chunker_version field.
	documentDescChunkerVersion := documentFields[8].Descriptor()
	// document.DefaultChunkerVersion holds the default value on creation for the chunker_version field.
	document.DefaultChunkerVersion = documentDescChunkerVersion.Default.(int)
	// documentDescCapturedAt is the schema descriptor for captured_at field.
	documentDescCapturedAt := documentFields[11].Descriptor()
	// document.DefaultCapturedAt holds the default value on creation for the captured_at field.
	document.DefaultCapturedAt = documentDescCapturedAt.Default.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentFields[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() uuid.UUID)
	investigationjobFields := schema.InvestigationJob{}.Fields()
	_ = investigationjobFields
	// investigationjobDescIdempotencyKey is the schema descriptor for idempotency_key field.
	investigationjobDescIdempotencyKey := investigationjobFields[1].Descriptor()
	// investigationjob.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	investigationjob.IdempotencyKeyValidator = investigationjobDescIdempotencyKey.Validators[0].(func(string) error)
	// investigationjobDescDescription is the schema descriptor for description field.
	investigationjobDescDescription := investigationjobFields[2].Descriptor()
	// investigationjob.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	investigationjob.DescriptionValidator = investigationjobDescDescription.Validators[0].(func(string) error)
	// investigationjobDescStatus is the schema descriptor for status field.
	investigationjobDescStatus := investigationjobFields[3].Descriptor()
	// investigationjob.DefaultStatus holds the default value on creation for the status field.
	investigationjob.DefaultStatus = investigationjobDescStatus.Default.(string)
	// investigationjobDescIterations is the schema descriptor for iterations field.
	investigationjobDescIterations := investigationjobFields[5].Descriptor()
	// investigationjob.DefaultIterations holds the default value on creation for the iterations field.
	investigationjob.DefaultIterations = investigationjobDescIterations.Default.(int)
	// investigationjobDescToolsUsed is the schema descriptor for tools_used field.
	investigationjobDescToolsUsed := investigationjobFields[6].Descriptor()
	// investigationjob.DefaultToolsUsed holds the default value on creation for the tools_used field.
	investigationjob.DefaultToolsUsed = investigationjobDescToolsUsed.Default.(int)
	// investigationjobDescCreatedAt is the schema descriptor for created_at field.
	investigationjobDescCreatedAt := investigationjobFields[8].Descriptor()
	// investigationjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	investigationjob.DefaultCreatedAt = investigationjobDescCreatedAt.Default.(func() time.Time)
	// investigationjobDescUpdatedAt is the schema descriptor for updated_at field.
	investigationjobDescUpdatedAt := investigationjobFields[9].Descriptor()
	// investigationjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	investigationjob.DefaultUpdatedAt = investigationjobDescUpdatedAt.Default.(func() time.Time)
	// investigationjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	investigationjob.UpdateDefaultUpdatedAt = investigationjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// investigationjobDescID is the schema descriptor for id field.
	investigationjobDescID := investigationjobFields[0].Descriptor()
	// investigationjob.DefaultID holds the default value on creation for the id field.
	investigationjob.DefaultID = investigationjobDescID.Default.(func() uuid.UUID)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescDedupKey is the schema descriptor for dedup_key field.
	notificationDescDedupKey := notificationFields[1].Descriptor()
	// notification.DedupKeyValidator is a validator for the "dedup_key" field. It is called by the builders before save.
	notification.DedupKeyValidator = notificationDescDedupKey.Validators[0].(func(string) error)
	// notificationDescChannel is the schema descriptor for channel field.
	notificationDescChannel := notificationFields[3].Descriptor()
	// notification.ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	notification.ChannelValidator = notificationDescChannel.Validators[0].(func(string) error)
	// notificationDescSource is the schema descriptor for source field.
	notificationDescSource := notificationFields[6].Descriptor()
	// notification.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	notification.SourceValidator = notificationDescSource.Validators[0].(func(string) error)
	// notificationDescEventType is the schema descriptor for event_type field.
	notificationDescEventType := notificationFields[7].Descriptor()
	// notification.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	notification.EventTypeValidator = notificationDescEventType.Validators[0].(func(string) error)
	// notificationDescText is the schema descriptor for text field.
	notificationDescText := notificationFields[8].Descriptor()
	// notification.TextValidator is a validator for the "text" field. It is called by the builders before save.
	notification.TextValidator = notificationDescText.Validators[0].(func(string) error)
	// notificationDescStatus is the schema descriptor for status field.
	notificationDescStatus := notificationFields[10].Descriptor()
	// notification.DefaultStatus holds the default value on creation for the status field.
	notification.DefaultStatus = notificationDescStatus.Default.(string)
	// notificationDescAttempts is the schema descriptor for attempts field.
	notificationDescAttempts := notificationFields[11].Descriptor()
	// notification.DefaultAttempts holds the default value on creation for the attempts field.
	notification.DefaultAttempts = notificationDescAttempts.Default.(int)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[13].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationFields[14].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	notifysubscriptionFields := schema.NotifySubscription{}.Fields()
	_ = notifysubscriptionFields
	// notifysubscriptionDescSource is the schema descriptor for source field.
	notifysubscriptionDescSource := notifysubscriptionFields[2].Descriptor()
	// notifysubscription.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	notifysubscription.SourceValidator = notifysubscriptionDescSource.Validators[0].(func(string) error)
	// notifysubscriptionDescEventTypes is the schema descriptor for event_types field.
	notifysubscriptionDescEventTypes := notifysubscriptionFields[3].Descriptor()
	// notifysubscription.DefaultEventTypes holds the default value on creation for the event_types field.
	notifysubscription.DefaultEventTypes = notifysubscriptionDescEventTypes.Default.([]string)
	// notifysubscriptionDescFilters is the schema descriptor for filters field.
	notifysubscriptionDescFilters := notifysubscriptionFields[4].Descriptor()
	// notifysubscription.DefaultFilters holds the default value on creation for the filters field.
	notifysubscription.DefaultFilters = notifysubscriptionDescFilters.Default.(map[string]interface{})
	// notifysubscriptionDescEnabled is the schema descriptor for enabled field.
	notifysubscriptionDescEnabled := notifysubscriptionFields[5].Descriptor()
	// notifysubscription.DefaultEnabled holds the default value on creation for the enabled field.
	notifysubscription.DefaultEnabled = notifysubscriptionDescEnabled.Default.(bool)
	// notifysubscriptionDescCreatedAt is the schema descriptor for created_at field.
	notifysubscriptionDescCreatedAt := notifysubscriptionFields[6].Descriptor()
	// notifysubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	notifysubscription.DefaultCreatedAt = notifysubscriptionDescCreatedAt.Default.(func() time.Time)
	// notifysubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	notifysubscriptionDescUpdatedAt := notifysubscriptionFields[7].Descriptor()
	// notifysubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notifysubscription.DefaultUpdatedAt = notifysubscriptionDescUpdatedAt.Default.(func() time.Time)
	// notifysubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notifysubscription.UpdateDefaultUpdatedAt = notifysubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notifysubscriptionDescID is the schema descriptor for id field.
	notifysubscriptionDescID := notifysubscriptionFields[0].Descriptor()
	// notifysubscription.DefaultID holds the default value on creation for the id field.
	notifysubscription.DefaultID = notifysubscriptionDescID.Default.(func() uuid.UUID)
	supportrequestFields := schema.SupportRequest{}.Fields()
	_ = supportrequestFields
	// supportrequestDescRawText is the schema descriptor for raw_text field.
	supportrequestDescRawText := supportrequestFields[5].Descriptor()
	// supportrequest.RawTextValidator is a validator for the "raw_text" field. It is called by the builders before save.
	supportrequest.RawTextValidator = supportrequestDescRawText.Validators[0].(func(string) error)
	// supportrequestDescStatus is the schema descriptor for status field.
	supportrequestDescStatus := supportrequestFields[9].Descriptor()
	// supportrequest.DefaultStatus holds the default value on creation for the status field.
	supportrequest.DefaultStatus = supportrequestDescStatus.Default.(string)
	// supportrequestDescMetadata is the schema descriptor for metadata field.
	supportrequestDescMetadata := supportrequestFields[11].Descriptor()
	// supportrequest.DefaultMetadata holds the default value on creation for the metadata field.
	supportrequest.DefaultMetadata = supportrequestDescMetadata.Default.(map[string]interface{})
	// supportrequestDescCreatedAt is the schema descriptor for created_at field.
	supportrequestDescCreatedAt := supportrequestFields[12].Descriptor()
	// supportrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	supportrequest.DefaultCreatedAt = supportrequestDescCreatedAt.Default.(func() time.Time)
	// supportrequestDescUpdatedAt is the schema descriptor for updated_at field.
	supportrequestDescUpdatedAt := supportrequestFields[13].Descriptor()
	// supportrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	supportrequest.DefaultUpdatedAt = supportrequestDescUpdatedAt.Default.(func() time.Time)
	// supportrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	supportrequest.UpdateDefaultUpdatedAt = supportrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	// supportrequestDescID is the schema descriptor for id field.
	supportrequestDescID := supportrequestFields[0].Descriptor()
	// supportrequest.DefaultID holds the default value on creation for the id field.
	supportrequest.DefaultID = supportrequestDescID.Default.(func() uuid.UUID)
	syncstateFields := schema.SyncState{}.Fields()
	_ = syncstateFields
	// syncstateDescSource is the schema descriptor for source field.
	syncstateDescSource := syncstateFields[1].Descriptor()
	// syncstate.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	syncstate.SourceValidator = syncstateDescSource.Validators[0].(func(string) error)
	// syncstateDescLastCursor is the schema descriptor for last_cursor field.
	syncstateDescLastCursor := syncstateFields[3].Descriptor()
	// syncstate.DefaultLastCursor holds the default value on creation for the last_cursor field.
	syncstate.DefaultLastCursor = syncstateDescLastCursor.Default.(string)
	// syncstateDescStatus is the schema descriptor for status field.
	syncstateDescStatus := syncstateFields[4].Descriptor()
	// syncstate.DefaultStatus holds the default value on creation for the status field.
	syncstate.DefaultStatus = syncstateDescStatus.Default.(string)
	// syncstateDescDocumentCount is the schema descriptor for document_count field.
	syncstateDescDocumentCount := syncstateFields[6].Descriptor()
	// syncstate.DefaultDocumentCount holds the default value on creation for the document_count field.
	syncstate.DefaultDocumentCount = syncstateDescDocumentCount.Default.(int)
	// syncstateDescUpdatedAt is the schema descriptor for updated_at field.
	syncstateDescUpdatedAt := syncstateFields[7].Descriptor()
	// syncstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	syncstate.DefaultUpdatedAt = syncstateDescUpdatedAt.Default.(func() time.Time)
	// syncstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	syncstate.UpdateDefaultUpdatedAt = syncstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// syncstateDescID is the schema descriptor for id field.
	syncstateDescID := syncstateFields[0].Descriptor()
	// syncstate.DefaultID holds the default value on creation for the id field.
	syncstate.DefaultID = syncstateDescID.Default.(func() uuid.UUID)
	telegrammessageFields := schema.TelegramMessage{}.Fields()
	_ = telegrammessageFields
	// telegrammessageDescRawJSON is the schema descriptor for raw_json field.
	telegrammessageDescRawJSON := telegrammessageFields[9].Descriptor()
	// telegrammessage.DefaultRawJSON holds the default value on creation for the raw_json field.
	telegrammessage.DefaultRawJSON = telegrammessageDescRawJSON.Default.(map[string]interface{})
	// telegrammessageDescCreatedAt is the schema descriptor for created_at field.
	telegrammessageDescCreatedAt := telegrammessageFields[10].Descriptor()
	// telegrammessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	telegrammessage.DefaultCreatedAt = telegrammessageDescCreatedAt.Default.(func() time.Time)
	// telegrammessageDescID is the schema descriptor for id field.
	telegrammessageDescID := telegrammessageFields[0].Descriptor()
	// telegrammessage.DefaultID holds the default value on creation for the id field.
	telegrammessage.DefaultID = telegrammessageDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEnabled is the schema descriptor for enabled field.
	userDescEnabled := userFields[6].Descriptor()
	// user.DefaultEnabled holds the default value on creation for the enabled field.
	user.DefaultEnabled = userDescEnabled.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	usertokenFields := schema.UserToken{}.Fields()
	_ = usertokenFields
	// usertokenDescName is the schema descriptor for name field.
	usertokenDescName := usertokenFields[2].Descriptor()
	// usertoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	usertoken.NameValidator = usertokenDescName.Validators[0].(func(string) error)
	// usertokenDescTokenHash is the schema descriptor for token_hash field.
	usertokenDescTokenHash := usertokenFields[3].Descriptor()
	// usertoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	usertoken.TokenHashValidator = usertokenDescTokenHash.Validators[0].(func(string) error)
	// usertokenDescTokenPrefix is the schema descriptor for token_prefix field.
	usertokenDescTokenPrefix := usertokenFields[4].Descriptor()
	// usertoken.TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	usertoken.TokenPrefixValidator = usertokenDescTokenPrefix.Validators[0].(func(string) error)
	// usertokenDescCreatedAt is the schema descriptor for created_at field.
	usertokenDescCreatedAt := usertokenFields[5].Descriptor()
	// usertoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	usertoken.DefaultCreatedAt = usertokenDescCreatedAt.Default.(func() time.Time)
	// usertokenDescID is the schema descriptor for id field.
	usertokenDescID := usertokenFields[0].Descriptor()
	// usertoken.DefaultID holds the default value on creation for the id field.
	usertoken.DefaultID = usertokenDescID.Default.(func() uuid.UUID)
}
