// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/go-faster/scpbot/internal/ent/chunk"
	"github.com/go-faster/scpbot/internal/ent/document"
	"github.com/go-faster/scpbot/internal/ent/schema"
	"github.com/go-faster/scpbot/internal/ent/supportrequest"
	"github.com/go-faster/scpbot/internal/ent/syncstate"
	"github.com/go-faster/scpbot/internal/ent/telegrammessage"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chunkFields := schema.Chunk{}.Fields()
	_ = chunkFields
	// chunkDescChunkType is the schema descriptor for chunk_type field.
	chunkDescChunkType := chunkFields[3].Descriptor()
	// chunk.ChunkTypeValidator is a validator for the "chunk_type" field. It is called by the builders before save.
	chunk.ChunkTypeValidator = chunkDescChunkType.Validators[0].(func(string) error)
	// chunkDescText is the schema descriptor for text field.
	chunkDescText := chunkFields[5].Descriptor()
	// chunk.TextValidator is a validator for the "text" field. It is called by the builders before save.
	chunk.TextValidator = chunkDescText.Validators[0].(func(string) error)
	// chunkDescTextHash is the schema descriptor for text_hash field.
	chunkDescTextHash := chunkFields[6].Descriptor()
	// chunk.TextHashValidator is a validator for the "text_hash" field. It is called by the builders before save.
	chunk.TextHashValidator = chunkDescTextHash.Validators[0].(func(string) error)
	// chunkDescMetadata is the schema descriptor for metadata field.
	chunkDescMetadata := chunkFields[7].Descriptor()
	// chunk.DefaultMetadata holds the default value on creation for the metadata field.
	chunk.DefaultMetadata = chunkDescMetadata.Default.(map[string]interface{})
	// chunkDescID is the schema descriptor for id field.
	chunkDescID := chunkFields[0].Descriptor()
	// chunk.DefaultID holds the default value on creation for the id field.
	chunk.DefaultID = chunkDescID.Default.(func() uuid.UUID)
	documentFields := schema.Document{}.Fields()
	_ = documentFields
	// documentDescSource is the schema descriptor for source field.
	documentDescSource := documentFields[1].Descriptor()
	// document.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	document.SourceValidator = documentDescSource.Validators[0].(func(string) error)
	// documentDescSourceID is the schema descriptor for source_id field.
	documentDescSourceID := documentFields[2].Descriptor()
	// document.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	document.SourceIDValidator = documentDescSourceID.Validators[0].(func(string) error)
	// documentDescBodyHash is the schema descriptor for body_hash field.
	documentDescBodyHash := documentFields[6].Descriptor()
	// document.BodyHashValidator is a validator for the "body_hash" field. It is called by the builders before save.
	document.BodyHashValidator = documentDescBodyHash.Validators[0].(func(string) error)
	// documentDescMetadata is the schema descriptor for metadata field.
	documentDescMetadata := documentFields[7].Descriptor()
	// document.DefaultMetadata holds the default value on creation for the metadata field.
	document.DefaultMetadata = documentDescMetadata.Default.(map[string]interface{})
	// documentDescCapturedAt is the schema descriptor for captured_at field.
	documentDescCapturedAt := documentFields[10].Descriptor()
	// document.DefaultCapturedAt holds the default value on creation for the captured_at field.
	document.DefaultCapturedAt = documentDescCapturedAt.Default.(func() time.Time)
	// documentDescID is the schema descriptor for id field.
	documentDescID := documentFields[0].Descriptor()
	// document.DefaultID holds the default value on creation for the id field.
	document.DefaultID = documentDescID.Default.(func() uuid.UUID)
	supportrequestFields := schema.SupportRequest{}.Fields()
	_ = supportrequestFields
	// supportrequestDescRawText is the schema descriptor for raw_text field.
	supportrequestDescRawText := supportrequestFields[5].Descriptor()
	// supportrequest.RawTextValidator is a validator for the "raw_text" field. It is called by the builders before save.
	supportrequest.RawTextValidator = supportrequestDescRawText.Validators[0].(func(string) error)
	// supportrequestDescStatus is the schema descriptor for status field.
	supportrequestDescStatus := supportrequestFields[9].Descriptor()
	// supportrequest.DefaultStatus holds the default value on creation for the status field.
	supportrequest.DefaultStatus = supportrequestDescStatus.Default.(string)
	// supportrequestDescMetadata is the schema descriptor for metadata field.
	supportrequestDescMetadata := supportrequestFields[11].Descriptor()
	// supportrequest.DefaultMetadata holds the default value on creation for the metadata field.
	supportrequest.DefaultMetadata = supportrequestDescMetadata.Default.(map[string]interface{})
	// supportrequestDescCreatedAt is the schema descriptor for created_at field.
	supportrequestDescCreatedAt := supportrequestFields[12].Descriptor()
	// supportrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	supportrequest.DefaultCreatedAt = supportrequestDescCreatedAt.Default.(func() time.Time)
	// supportrequestDescUpdatedAt is the schema descriptor for updated_at field.
	supportrequestDescUpdatedAt := supportrequestFields[13].Descriptor()
	// supportrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	supportrequest.DefaultUpdatedAt = supportrequestDescUpdatedAt.Default.(func() time.Time)
	// supportrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	supportrequest.UpdateDefaultUpdatedAt = supportrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	// supportrequestDescID is the schema descriptor for id field.
	supportrequestDescID := supportrequestFields[0].Descriptor()
	// supportrequest.DefaultID holds the default value on creation for the id field.
	supportrequest.DefaultID = supportrequestDescID.Default.(func() uuid.UUID)
	syncstateFields := schema.SyncState{}.Fields()
	_ = syncstateFields
	// syncstateDescSource is the schema descriptor for source field.
	syncstateDescSource := syncstateFields[1].Descriptor()
	// syncstate.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	syncstate.SourceValidator = syncstateDescSource.Validators[0].(func(string) error)
	// syncstateDescLastCursor is the schema descriptor for last_cursor field.
	syncstateDescLastCursor := syncstateFields[3].Descriptor()
	// syncstate.DefaultLastCursor holds the default value on creation for the last_cursor field.
	syncstate.DefaultLastCursor = syncstateDescLastCursor.Default.(string)
	// syncstate.LastCursorValidator is a validator for the "last_cursor" field. It is called by the builders before save.
	syncstate.LastCursorValidator = syncstateDescLastCursor.Validators[0].(func(string) error)
	// syncstateDescStatus is the schema descriptor for status field.
	syncstateDescStatus := syncstateFields[4].Descriptor()
	// syncstate.DefaultStatus holds the default value on creation for the status field.
	syncstate.DefaultStatus = syncstateDescStatus.Default.(string)
	// syncstateDescDocumentCount is the schema descriptor for document_count field.
	syncstateDescDocumentCount := syncstateFields[6].Descriptor()
	// syncstate.DefaultDocumentCount holds the default value on creation for the document_count field.
	syncstate.DefaultDocumentCount = syncstateDescDocumentCount.Default.(int)
	// syncstateDescUpdatedAt is the schema descriptor for updated_at field.
	syncstateDescUpdatedAt := syncstateFields[7].Descriptor()
	// syncstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	syncstate.DefaultUpdatedAt = syncstateDescUpdatedAt.Default.(func() time.Time)
	// syncstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	syncstate.UpdateDefaultUpdatedAt = syncstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	// syncstateDescID is the schema descriptor for id field.
	syncstateDescID := syncstateFields[0].Descriptor()
	// syncstate.DefaultID holds the default value on creation for the id field.
	syncstate.DefaultID = syncstateDescID.Default.(func() uuid.UUID)
	telegrammessageFields := schema.TelegramMessage{}.Fields()
	_ = telegrammessageFields
	// telegrammessageDescRawJSON is the schema descriptor for raw_json field.
	telegrammessageDescRawJSON := telegrammessageFields[9].Descriptor()
	// telegrammessage.DefaultRawJSON holds the default value on creation for the raw_json field.
	telegrammessage.DefaultRawJSON = telegrammessageDescRawJSON.Default.(map[string]interface{})
	// telegrammessageDescCreatedAt is the schema descriptor for created_at field.
	telegrammessageDescCreatedAt := telegrammessageFields[10].Descriptor()
	// telegrammessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	telegrammessage.DefaultCreatedAt = telegrammessageDescCreatedAt.Default.(func() time.Time)
	// telegrammessageDescID is the schema descriptor for id field.
	telegrammessageDescID := telegrammessageFields[0].Descriptor()
	// telegrammessage.DefaultID holds the default value on creation for the id field.
	telegrammessage.DefaultID = telegrammessageDescID.Default.(func() uuid.UUID)
}
