// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"github.com/go-faster/sisyphus/internal/ent/supportrequest"
)

// SupportRequestCreate is the builder for creating a SupportRequest entity.
type SupportRequestCreate struct {
	config
	mutation *SupportRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetChatID sets the "chat_id" field.
func (_c *SupportRequestCreate) SetChatID(v int64) *SupportRequestCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetFirstMessageID sets the "first_message_id" field.
func (_c *SupportRequestCreate) SetFirstMessageID(v int64) *SupportRequestCreate {
	_c.mutation.SetFirstMessageID(v)
	return _c
}

// SetLastMessageID sets the "last_message_id" field.
func (_c *SupportRequestCreate) SetLastMessageID(v int64) *SupportRequestCreate {
	_c.mutation.SetLastMessageID(v)
	return _c
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableLastMessageID(v *int64) *SupportRequestCreate {
	if v != nil {
		_c.SetLastMessageID(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *SupportRequestCreate) SetSourceURL(v string) *SupportRequestCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableSourceURL(v *string) *SupportRequestCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetRawText sets the "raw_text" field.
func (_c *SupportRequestCreate) SetRawText(v string) *SupportRequestCreate {
	_c.mutation.SetRawText(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *SupportRequestCreate) SetSummary(v string) *SupportRequestCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableSummary(v *string) *SupportRequestCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetServiceGuess sets the "service_guess" field.
func (_c *SupportRequestCreate) SetServiceGuess(v string) *SupportRequestCreate {
	_c.mutation.SetServiceGuess(v)
	return _c
}

// SetNillableServiceGuess sets the "service_guess" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableServiceGuess(v *string) *SupportRequestCreate {
	if v != nil {
		_c.SetServiceGuess(*v)
	}
	return _c
}

// SetSeverityGuess sets the "severity_guess" field.
func (_c *SupportRequestCreate) SetSeverityGuess(v string) *SupportRequestCreate {
	_c.mutation.SetSeverityGuess(v)
	return _c
}

// SetNillableSeverityGuess sets the "severity_guess" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableSeverityGuess(v *string) *SupportRequestCreate {
	if v != nil {
		_c.SetSeverityGuess(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupportRequestCreate) SetStatus(v string) *SupportRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableStatus(v *string) *SupportRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *SupportRequestCreate) SetConfidence(v float64) *SupportRequestCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableConfidence(v *float64) *SupportRequestCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SupportRequestCreate) SetMetadata(v map[string]interface{}) *SupportRequestCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupportRequestCreate) SetCreatedAt(v time.Time) *SupportRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableCreatedAt(v *time.Time) *SupportRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupportRequestCreate) SetUpdatedAt(v time.Time) *SupportRequestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableUpdatedAt(v *time.Time) *SupportRequestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SupportRequestCreate) SetID(v uuid.UUID) *SupportRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SupportRequestCreate) SetNillableID(v *uuid.UUID) *SupportRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SupportRequestMutation object of the builder.
func (_c *SupportRequestCreate) Mutation() *SupportRequestMutation {
	return _c.mutation
}

// Save creates the SupportRequest in the database.
func (_c *SupportRequestCreate) Save(ctx context.Context) (*SupportRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupportRequestCreate) SaveX(ctx context.Context) *SupportRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupportRequestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := supportrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := supportrequest.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supportrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := supportrequest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := supportrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupportRequestCreate) check() error {
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "SupportRequest.chat_id"`)}
	}
	if _, ok := _c.mutation.FirstMessageID(); !ok {
		return &ValidationError{Name: "first_message_id", err: errors.New(`ent: missing required field "SupportRequest.first_message_id"`)}
	}
	if _, ok := _c.mutation.RawText(); !ok {
		return &ValidationError{Name: "raw_text", err: errors.New(`ent: missing required field "SupportRequest.raw_text"`)}
	}
	if v, ok := _c.mutation.RawText(); ok {
		if err := supportrequest.RawTextValidator(v); err != nil {
			return &ValidationError{Name: "raw_text", err: fmt.Errorf(`ent: validator failed for field "SupportRequest.raw_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupportRequest.status"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "SupportRequest.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupportRequest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupportRequest.updated_at"`)}
	}
	return nil
}

func (_c *SupportRequestCreate) sqlSave(ctx context.Context) (*SupportRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupportRequestCreate) createSpec() (*SupportRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &SupportRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supportrequest.Table, sqlgraph.NewFieldSpec(supportrequest.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(supportrequest.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.FirstMessageID(); ok {
		_spec.SetField(supportrequest.FieldFirstMessageID, field.TypeInt64, value)
		_node.FirstMessageID = value
	}
	if value, ok := _c.mutation.LastMessageID(); ok {
		_spec.SetField(supportrequest.FieldLastMessageID, field.TypeInt64, value)
		_node.LastMessageID = &value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(supportrequest.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.RawText(); ok {
		_spec.SetField(supportrequest.FieldRawText, field.TypeString, value)
		_node.RawText = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(supportrequest.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.ServiceGuess(); ok {
		_spec.SetField(supportrequest.FieldServiceGuess, field.TypeString, value)
		_node.ServiceGuess = value
	}
	if value, ok := _c.mutation.SeverityGuess(); ok {
		_spec.SetField(supportrequest.FieldSeverityGuess, field.TypeString, value)
		_node.SeverityGuess = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supportrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(supportrequest.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(supportrequest.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supportrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supportrequest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportRequest.Create().
//		SetChatID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportRequestUpsert) {
//			SetChatID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportRequestCreate) OnConflict(opts ...sql.ConflictOption) *SupportRequestUpsertOne {
	_c.conflict = opts
	return &SupportRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportRequestCreate) OnConflictColumns(columns ...string) *SupportRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportRequestUpsertOne{
		create: _c,
	}
}

type (
	// SupportRequestUpsertOne is the builder for "upsert"-ing
	//  one SupportRequest node.
	SupportRequestUpsertOne struct {
		create *SupportRequestCreate
	}

	// SupportRequestUpsert is the "OnConflict" setter.
	SupportRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetChatID sets the "chat_id" field.
func (u *SupportRequestUpsert) SetChatID(v int64) *SupportRequestUpsert {
	u.Set(supportrequest.FieldChatID, v)
	return u
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateChatID() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldChatID)
	return u
}

// AddChatID adds v to the "chat_id" field.
func (u *SupportRequestUpsert) AddChatID(v int64) *SupportRequestUpsert {
	u.Add(supportrequest.FieldChatID, v)
	return u
}

// SetFirstMessageID sets the "first_message_id" field.
func (u *SupportRequestUpsert) SetFirstMessageID(v int64) *SupportRequestUpsert {
	u.Set(supportrequest.FieldFirstMessageID, v)
	return u
}

// UpdateFirstMessageID sets the "first_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateFirstMessageID() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldFirstMessageID)
	return u
}

// AddFirstMessageID adds v to the "first_message_id" field.
func (u *SupportRequestUpsert) AddFirstMessageID(v int64) *SupportRequestUpsert {
	u.Add(supportrequest.FieldFirstMessageID, v)
	return u
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportRequestUpsert) SetLastMessageID(v int64) *SupportRequestUpsert {
	u.Set(supportrequest.FieldLastMessageID, v)
	return u
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateLastMessageID() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldLastMessageID)
	return u
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportRequestUpsert) AddLastMessageID(v int64) *SupportRequestUpsert {
	u.Add(supportrequest.FieldLastMessageID, v)
	return u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportRequestUpsert) ClearLastMessageID() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldLastMessageID)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *SupportRequestUpsert) SetSourceURL(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateSourceURL() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldSourceURL)
	return u
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SupportRequestUpsert) ClearSourceURL() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldSourceURL)
	return u
}

// SetRawText sets the "raw_text" field.
func (u *SupportRequestUpsert) SetRawText(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldRawText, v)
	return u
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateRawText() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldRawText)
	return u
}

// SetSummary sets the "summary" field.
func (u *SupportRequestUpsert) SetSummary(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateSummary() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldSummary)
	return u
}

// ClearSummary clears the value of the "summary" field.
func (u *SupportRequestUpsert) ClearSummary() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldSummary)
	return u
}

// SetServiceGuess sets the "service_guess" field.
func (u *SupportRequestUpsert) SetServiceGuess(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldServiceGuess, v)
	return u
}

// UpdateServiceGuess sets the "service_guess" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateServiceGuess() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldServiceGuess)
	return u
}

// ClearServiceGuess clears the value of the "service_guess" field.
func (u *SupportRequestUpsert) ClearServiceGuess() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldServiceGuess)
	return u
}

// SetSeverityGuess sets the "severity_guess" field.
func (u *SupportRequestUpsert) SetSeverityGuess(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldSeverityGuess, v)
	return u
}

// UpdateSeverityGuess sets the "severity_guess" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateSeverityGuess() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldSeverityGuess)
	return u
}

// ClearSeverityGuess clears the value of the "severity_guess" field.
func (u *SupportRequestUpsert) ClearSeverityGuess() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldSeverityGuess)
	return u
}

// SetStatus sets the "status" field.
func (u *SupportRequestUpsert) SetStatus(v string) *SupportRequestUpsert {
	u.Set(supportrequest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateStatus() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldStatus)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *SupportRequestUpsert) SetConfidence(v float64) *SupportRequestUpsert {
	u.Set(supportrequest.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateConfidence() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldConfidence)
	return u
}

// AddConfidence adds v to the "confidence" field.
func (u *SupportRequestUpsert) AddConfidence(v float64) *SupportRequestUpsert {
	u.Add(supportrequest.FieldConfidence, v)
	return u
}

// ClearConfidence clears the value of the "confidence" field.
func (u *SupportRequestUpsert) ClearConfidence() *SupportRequestUpsert {
	u.SetNull(supportrequest.FieldConfidence)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SupportRequestUpsert) SetMetadata(v map[string]interface{}) *SupportRequestUpsert {
	u.Set(supportrequest.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateMetadata() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldMetadata)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SupportRequestUpsert) SetCreatedAt(v time.Time) *SupportRequestUpsert {
	u.Set(supportrequest.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateCreatedAt() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportRequestUpsert) SetUpdatedAt(v time.Time) *SupportRequestUpsert {
	u.Set(supportrequest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportRequestUpsert) UpdateUpdatedAt() *SupportRequestUpsert {
	u.SetExcluded(supportrequest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supportrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupportRequestUpsertOne) UpdateNewValues() *SupportRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(supportrequest.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupportRequestUpsertOne) Ignore() *SupportRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportRequestUpsertOne) DoNothing() *SupportRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportRequestCreate.OnConflict
// documentation for more info.
func (u *SupportRequestUpsertOne) Update(set func(*SupportRequestUpsert)) *SupportRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetChatID sets the "chat_id" field.
func (u *SupportRequestUpsertOne) SetChatID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetChatID(v)
	})
}

// AddChatID adds v to the "chat_id" field.
func (u *SupportRequestUpsertOne) AddChatID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateChatID() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateChatID()
	})
}

// SetFirstMessageID sets the "first_message_id" field.
func (u *SupportRequestUpsertOne) SetFirstMessageID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetFirstMessageID(v)
	})
}

// AddFirstMessageID adds v to the "first_message_id" field.
func (u *SupportRequestUpsertOne) AddFirstMessageID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddFirstMessageID(v)
	})
}

// UpdateFirstMessageID sets the "first_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateFirstMessageID() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateFirstMessageID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportRequestUpsertOne) SetLastMessageID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportRequestUpsertOne) AddLastMessageID(v int64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateLastMessageID() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportRequestUpsertOne) ClearLastMessageID() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearLastMessageID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SupportRequestUpsertOne) SetSourceURL(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateSourceURL() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SupportRequestUpsertOne) ClearSourceURL() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSourceURL()
	})
}

// SetRawText sets the "raw_text" field.
func (u *SupportRequestUpsertOne) SetRawText(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetRawText(v)
	})
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateRawText() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateRawText()
	})
}

// SetSummary sets the "summary" field.
func (u *SupportRequestUpsertOne) SetSummary(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateSummary() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *SupportRequestUpsertOne) ClearSummary() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSummary()
	})
}

// SetServiceGuess sets the "service_guess" field.
func (u *SupportRequestUpsertOne) SetServiceGuess(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetServiceGuess(v)
	})
}

// UpdateServiceGuess sets the "service_guess" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateServiceGuess() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateServiceGuess()
	})
}

// ClearServiceGuess clears the value of the "service_guess" field.
func (u *SupportRequestUpsertOne) ClearServiceGuess() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearServiceGuess()
	})
}

// SetSeverityGuess sets the "severity_guess" field.
func (u *SupportRequestUpsertOne) SetSeverityGuess(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSeverityGuess(v)
	})
}

// UpdateSeverityGuess sets the "severity_guess" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateSeverityGuess() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSeverityGuess()
	})
}

// ClearSeverityGuess clears the value of the "severity_guess" field.
func (u *SupportRequestUpsertOne) ClearSeverityGuess() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSeverityGuess()
	})
}

// SetStatus sets the "status" field.
func (u *SupportRequestUpsertOne) SetStatus(v string) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateStatus() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetConfidence sets the "confidence" field.
func (u *SupportRequestUpsertOne) SetConfidence(v float64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *SupportRequestUpsertOne) AddConfidence(v float64) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateConfidence() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateConfidence()
	})
}

// ClearConfidence clears the value of the "confidence" field.
func (u *SupportRequestUpsertOne) ClearConfidence() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearConfidence()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SupportRequestUpsertOne) SetMetadata(v map[string]interface{}) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateMetadata() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SupportRequestUpsertOne) SetCreatedAt(v time.Time) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateCreatedAt() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportRequestUpsertOne) SetUpdatedAt(v time.Time) *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportRequestUpsertOne) UpdateUpdatedAt() *SupportRequestUpsertOne {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupportRequestUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SupportRequestUpsertOne.ID is not supported by MySQL driver. Use SupportRequestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupportRequestUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupportRequestCreateBulk is the builder for creating many SupportRequest entities in bulk.
type SupportRequestCreateBulk struct {
	config
	err      error
	builders []*SupportRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the SupportRequest entities in the database.
func (_c *SupportRequestCreateBulk) Save(ctx context.Context) ([]*SupportRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupportRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupportRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupportRequestCreateBulk) SaveX(ctx context.Context) []*SupportRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupportRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupportRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupportRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupportRequestUpsert) {
//			SetChatID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupportRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupportRequestUpsertBulk {
	_c.conflict = opts
	return &SupportRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupportRequestCreateBulk) OnConflictColumns(columns ...string) *SupportRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupportRequestUpsertBulk{
		create: _c,
	}
}

// SupportRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of SupportRequest nodes.
type SupportRequestUpsertBulk struct {
	create *SupportRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supportrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupportRequestUpsertBulk) UpdateNewValues() *SupportRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(supportrequest.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupportRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupportRequestUpsertBulk) Ignore() *SupportRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupportRequestUpsertBulk) DoNothing() *SupportRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupportRequestCreateBulk.OnConflict
// documentation for more info.
func (u *SupportRequestUpsertBulk) Update(set func(*SupportRequestUpsert)) *SupportRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupportRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetChatID sets the "chat_id" field.
func (u *SupportRequestUpsertBulk) SetChatID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetChatID(v)
	})
}

// AddChatID adds v to the "chat_id" field.
func (u *SupportRequestUpsertBulk) AddChatID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateChatID() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateChatID()
	})
}

// SetFirstMessageID sets the "first_message_id" field.
func (u *SupportRequestUpsertBulk) SetFirstMessageID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetFirstMessageID(v)
	})
}

// AddFirstMessageID adds v to the "first_message_id" field.
func (u *SupportRequestUpsertBulk) AddFirstMessageID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddFirstMessageID(v)
	})
}

// UpdateFirstMessageID sets the "first_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateFirstMessageID() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateFirstMessageID()
	})
}

// SetLastMessageID sets the "last_message_id" field.
func (u *SupportRequestUpsertBulk) SetLastMessageID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetLastMessageID(v)
	})
}

// AddLastMessageID adds v to the "last_message_id" field.
func (u *SupportRequestUpsertBulk) AddLastMessageID(v int64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddLastMessageID(v)
	})
}

// UpdateLastMessageID sets the "last_message_id" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateLastMessageID() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateLastMessageID()
	})
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (u *SupportRequestUpsertBulk) ClearLastMessageID() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearLastMessageID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SupportRequestUpsertBulk) SetSourceURL(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateSourceURL() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SupportRequestUpsertBulk) ClearSourceURL() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSourceURL()
	})
}

// SetRawText sets the "raw_text" field.
func (u *SupportRequestUpsertBulk) SetRawText(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetRawText(v)
	})
}

// UpdateRawText sets the "raw_text" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateRawText() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateRawText()
	})
}

// SetSummary sets the "summary" field.
func (u *SupportRequestUpsertBulk) SetSummary(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateSummary() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSummary()
	})
}

// ClearSummary clears the value of the "summary" field.
func (u *SupportRequestUpsertBulk) ClearSummary() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSummary()
	})
}

// SetServiceGuess sets the "service_guess" field.
func (u *SupportRequestUpsertBulk) SetServiceGuess(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetServiceGuess(v)
	})
}

// UpdateServiceGuess sets the "service_guess" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateServiceGuess() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateServiceGuess()
	})
}

// ClearServiceGuess clears the value of the "service_guess" field.
func (u *SupportRequestUpsertBulk) ClearServiceGuess() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearServiceGuess()
	})
}

// SetSeverityGuess sets the "severity_guess" field.
func (u *SupportRequestUpsertBulk) SetSeverityGuess(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetSeverityGuess(v)
	})
}

// UpdateSeverityGuess sets the "severity_guess" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateSeverityGuess() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateSeverityGuess()
	})
}

// ClearSeverityGuess clears the value of the "severity_guess" field.
func (u *SupportRequestUpsertBulk) ClearSeverityGuess() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearSeverityGuess()
	})
}

// SetStatus sets the "status" field.
func (u *SupportRequestUpsertBulk) SetStatus(v string) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateStatus() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateStatus()
	})
}

// SetConfidence sets the "confidence" field.
func (u *SupportRequestUpsertBulk) SetConfidence(v float64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetConfidence(v)
	})
}

// AddConfidence adds v to the "confidence" field.
func (u *SupportRequestUpsertBulk) AddConfidence(v float64) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.AddConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateConfidence() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateConfidence()
	})
}

// ClearConfidence clears the value of the "confidence" field.
func (u *SupportRequestUpsertBulk) ClearConfidence() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.ClearConfidence()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SupportRequestUpsertBulk) SetMetadata(v map[string]interface{}) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateMetadata() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateMetadata()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SupportRequestUpsertBulk) SetCreatedAt(v time.Time) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateCreatedAt() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupportRequestUpsertBulk) SetUpdatedAt(v time.Time) *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupportRequestUpsertBulk) UpdateUpdatedAt() *SupportRequestUpsertBulk {
	return u.Update(func(s *SupportRequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupportRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupportRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupportRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupportRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
