// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/go-faster/sisyphus/internal/ent/predicate"
	"github.com/go-faster/sisyphus/internal/ent/supportrequest"
)

// SupportRequestUpdate is the builder for updating SupportRequest entities.
type SupportRequestUpdate struct {
	config
	hooks    []Hook
	mutation *SupportRequestMutation
}

// Where appends a list predicates to the SupportRequestUpdate builder.
func (_u *SupportRequestUpdate) Where(ps ...predicate.SupportRequest) *SupportRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *SupportRequestUpdate) SetChatID(v int64) *SupportRequestUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableChatID(v *int64) *SupportRequestUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *SupportRequestUpdate) AddChatID(v int64) *SupportRequestUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetFirstMessageID sets the "first_message_id" field.
func (_u *SupportRequestUpdate) SetFirstMessageID(v int64) *SupportRequestUpdate {
	_u.mutation.ResetFirstMessageID()
	_u.mutation.SetFirstMessageID(v)
	return _u
}

// SetNillableFirstMessageID sets the "first_message_id" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableFirstMessageID(v *int64) *SupportRequestUpdate {
	if v != nil {
		_u.SetFirstMessageID(*v)
	}
	return _u
}

// AddFirstMessageID adds value to the "first_message_id" field.
func (_u *SupportRequestUpdate) AddFirstMessageID(v int64) *SupportRequestUpdate {
	_u.mutation.AddFirstMessageID(v)
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *SupportRequestUpdate) SetLastMessageID(v int64) *SupportRequestUpdate {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableLastMessageID(v *int64) *SupportRequestUpdate {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *SupportRequestUpdate) AddLastMessageID(v int64) *SupportRequestUpdate {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *SupportRequestUpdate) ClearLastMessageID() *SupportRequestUpdate {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SupportRequestUpdate) SetSourceURL(v string) *SupportRequestUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableSourceURL(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *SupportRequestUpdate) ClearSourceURL() *SupportRequestUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetRawText sets the "raw_text" field.
func (_u *SupportRequestUpdate) SetRawText(v string) *SupportRequestUpdate {
	_u.mutation.SetRawText(v)
	return _u
}

// SetNillableRawText sets the "raw_text" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableRawText(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetRawText(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SupportRequestUpdate) SetSummary(v string) *SupportRequestUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableSummary(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SupportRequestUpdate) ClearSummary() *SupportRequestUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetServiceGuess sets the "service_guess" field.
func (_u *SupportRequestUpdate) SetServiceGuess(v string) *SupportRequestUpdate {
	_u.mutation.SetServiceGuess(v)
	return _u
}

// SetNillableServiceGuess sets the "service_guess" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableServiceGuess(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetServiceGuess(*v)
	}
	return _u
}

// ClearServiceGuess clears the value of the "service_guess" field.
func (_u *SupportRequestUpdate) ClearServiceGuess() *SupportRequestUpdate {
	_u.mutation.ClearServiceGuess()
	return _u
}

// SetSeverityGuess sets the "severity_guess" field.
func (_u *SupportRequestUpdate) SetSeverityGuess(v string) *SupportRequestUpdate {
	_u.mutation.SetSeverityGuess(v)
	return _u
}

// SetNillableSeverityGuess sets the "severity_guess" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableSeverityGuess(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetSeverityGuess(*v)
	}
	return _u
}

// ClearSeverityGuess clears the value of the "severity_guess" field.
func (_u *SupportRequestUpdate) ClearSeverityGuess() *SupportRequestUpdate {
	_u.mutation.ClearSeverityGuess()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportRequestUpdate) SetStatus(v string) *SupportRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableStatus(v *string) *SupportRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *SupportRequestUpdate) SetConfidence(v float64) *SupportRequestUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableConfidence(v *float64) *SupportRequestUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *SupportRequestUpdate) AddConfidence(v float64) *SupportRequestUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// ClearConfidence clears the value of the "confidence" field.
func (_u *SupportRequestUpdate) ClearConfidence() *SupportRequestUpdate {
	_u.mutation.ClearConfidence()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SupportRequestUpdate) SetMetadata(v map[string]interface{}) *SupportRequestUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SupportRequestUpdate) SetCreatedAt(v time.Time) *SupportRequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SupportRequestUpdate) SetNillableCreatedAt(v *time.Time) *SupportRequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportRequestUpdate) SetUpdatedAt(v time.Time) *SupportRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportRequestMutation object of the builder.
func (_u *SupportRequestUpdate) Mutation() *SupportRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupportRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupportRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportRequestUpdate) check() error {
	if v, ok := _u.mutation.RawText(); ok {
		if err := supportrequest.RawTextValidator(v); err != nil {
			return &ValidationError{Name: "raw_text", err: fmt.Errorf(`ent: validator failed for field "SupportRequest.raw_text": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportrequest.Table, supportrequest.Columns, sqlgraph.NewFieldSpec(supportrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(supportrequest.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(supportrequest.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstMessageID(); ok {
		_spec.SetField(supportrequest.FieldFirstMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFirstMessageID(); ok {
		_spec.AddField(supportrequest.FieldFirstMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(supportrequest.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(supportrequest.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(supportrequest.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(supportrequest.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(supportrequest.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.RawText(); ok {
		_spec.SetField(supportrequest.FieldRawText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(supportrequest.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(supportrequest.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceGuess(); ok {
		_spec.SetField(supportrequest.FieldServiceGuess, field.TypeString, value)
	}
	if _u.mutation.ServiceGuessCleared() {
		_spec.ClearField(supportrequest.FieldServiceGuess, field.TypeString)
	}
	if value, ok := _u.mutation.SeverityGuess(); ok {
		_spec.SetField(supportrequest.FieldSeverityGuess, field.TypeString, value)
	}
	if _u.mutation.SeverityGuessCleared() {
		_spec.ClearField(supportrequest.FieldSeverityGuess, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(supportrequest.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(supportrequest.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.ConfidenceCleared() {
		_spec.ClearField(supportrequest.FieldConfidence, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(supportrequest.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(supportrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupportRequestUpdateOne is the builder for updating a single SupportRequest entity.
type SupportRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupportRequestMutation
}

// SetChatID sets the "chat_id" field.
func (_u *SupportRequestUpdateOne) SetChatID(v int64) *SupportRequestUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableChatID(v *int64) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *SupportRequestUpdateOne) AddChatID(v int64) *SupportRequestUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetFirstMessageID sets the "first_message_id" field.
func (_u *SupportRequestUpdateOne) SetFirstMessageID(v int64) *SupportRequestUpdateOne {
	_u.mutation.ResetFirstMessageID()
	_u.mutation.SetFirstMessageID(v)
	return _u
}

// SetNillableFirstMessageID sets the "first_message_id" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableFirstMessageID(v *int64) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetFirstMessageID(*v)
	}
	return _u
}

// AddFirstMessageID adds value to the "first_message_id" field.
func (_u *SupportRequestUpdateOne) AddFirstMessageID(v int64) *SupportRequestUpdateOne {
	_u.mutation.AddFirstMessageID(v)
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *SupportRequestUpdateOne) SetLastMessageID(v int64) *SupportRequestUpdateOne {
	_u.mutation.ResetLastMessageID()
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableLastMessageID(v *int64) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// AddLastMessageID adds value to the "last_message_id" field.
func (_u *SupportRequestUpdateOne) AddLastMessageID(v int64) *SupportRequestUpdateOne {
	_u.mutation.AddLastMessageID(v)
	return _u
}

// ClearLastMessageID clears the value of the "last_message_id" field.
func (_u *SupportRequestUpdateOne) ClearLastMessageID() *SupportRequestUpdateOne {
	_u.mutation.ClearLastMessageID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SupportRequestUpdateOne) SetSourceURL(v string) *SupportRequestUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableSourceURL(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *SupportRequestUpdateOne) ClearSourceURL() *SupportRequestUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetRawText sets the "raw_text" field.
func (_u *SupportRequestUpdateOne) SetRawText(v string) *SupportRequestUpdateOne {
	_u.mutation.SetRawText(v)
	return _u
}

// SetNillableRawText sets the "raw_text" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableRawText(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetRawText(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SupportRequestUpdateOne) SetSummary(v string) *SupportRequestUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableSummary(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *SupportRequestUpdateOne) ClearSummary() *SupportRequestUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetServiceGuess sets the "service_guess" field.
func (_u *SupportRequestUpdateOne) SetServiceGuess(v string) *SupportRequestUpdateOne {
	_u.mutation.SetServiceGuess(v)
	return _u
}

// SetNillableServiceGuess sets the "service_guess" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableServiceGuess(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetServiceGuess(*v)
	}
	return _u
}

// ClearServiceGuess clears the value of the "service_guess" field.
func (_u *SupportRequestUpdateOne) ClearServiceGuess() *SupportRequestUpdateOne {
	_u.mutation.ClearServiceGuess()
	return _u
}

// SetSeverityGuess sets the "severity_guess" field.
func (_u *SupportRequestUpdateOne) SetSeverityGuess(v string) *SupportRequestUpdateOne {
	_u.mutation.SetSeverityGuess(v)
	return _u
}

// SetNillableSeverityGuess sets the "severity_guess" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableSeverityGuess(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetSeverityGuess(*v)
	}
	return _u
}

// ClearSeverityGuess clears the value of the "severity_guess" field.
func (_u *SupportRequestUpdateOne) ClearSeverityGuess() *SupportRequestUpdateOne {
	_u.mutation.ClearSeverityGuess()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupportRequestUpdateOne) SetStatus(v string) *SupportRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableStatus(v *string) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *SupportRequestUpdateOne) SetConfidence(v float64) *SupportRequestUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableConfidence(v *float64) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *SupportRequestUpdateOne) AddConfidence(v float64) *SupportRequestUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// ClearConfidence clears the value of the "confidence" field.
func (_u *SupportRequestUpdateOne) ClearConfidence() *SupportRequestUpdateOne {
	_u.mutation.ClearConfidence()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SupportRequestUpdateOne) SetMetadata(v map[string]interface{}) *SupportRequestUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SupportRequestUpdateOne) SetCreatedAt(v time.Time) *SupportRequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SupportRequestUpdateOne) SetNillableCreatedAt(v *time.Time) *SupportRequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupportRequestUpdateOne) SetUpdatedAt(v time.Time) *SupportRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SupportRequestMutation object of the builder.
func (_u *SupportRequestUpdateOne) Mutation() *SupportRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the SupportRequestUpdate builder.
func (_u *SupportRequestUpdateOne) Where(ps ...predicate.SupportRequest) *SupportRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupportRequestUpdateOne) Select(field string, fields ...string) *SupportRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupportRequest entity.
func (_u *SupportRequestUpdateOne) Save(ctx context.Context) (*SupportRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupportRequestUpdateOne) SaveX(ctx context.Context) *SupportRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupportRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupportRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupportRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supportrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupportRequestUpdateOne) check() error {
	if v, ok := _u.mutation.RawText(); ok {
		if err := supportrequest.RawTextValidator(v); err != nil {
			return &ValidationError{Name: "raw_text", err: fmt.Errorf(`ent: validator failed for field "SupportRequest.raw_text": %w`, err)}
		}
	}
	return nil
}

func (_u *SupportRequestUpdateOne) sqlSave(ctx context.Context) (_node *SupportRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supportrequest.Table, supportrequest.Columns, sqlgraph.NewFieldSpec(supportrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupportRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supportrequest.FieldID)
		for _, f := range fields {
			if !supportrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supportrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(supportrequest.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(supportrequest.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstMessageID(); ok {
		_spec.SetField(supportrequest.FieldFirstMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFirstMessageID(); ok {
		_spec.AddField(supportrequest.FieldFirstMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(supportrequest.FieldLastMessageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastMessageID(); ok {
		_spec.AddField(supportrequest.FieldLastMessageID, field.TypeInt64, value)
	}
	if _u.mutation.LastMessageIDCleared() {
		_spec.ClearField(supportrequest.FieldLastMessageID, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(supportrequest.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(supportrequest.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.RawText(); ok {
		_spec.SetField(supportrequest.FieldRawText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(supportrequest.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(supportrequest.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ServiceGuess(); ok {
		_spec.SetField(supportrequest.FieldServiceGuess, field.TypeString, value)
	}
	if _u.mutation.ServiceGuessCleared() {
		_spec.ClearField(supportrequest.FieldServiceGuess, field.TypeString)
	}
	if value, ok := _u.mutation.SeverityGuess(); ok {
		_spec.SetField(supportrequest.FieldSeverityGuess, field.TypeString, value)
	}
	if _u.mutation.SeverityGuessCleared() {
		_spec.ClearField(supportrequest.FieldSeverityGuess, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supportrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(supportrequest.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(supportrequest.FieldConfidence, field.TypeFloat64, value)
	}
	if _u.mutation.ConfidenceCleared() {
		_spec.ClearField(supportrequest.FieldConfidence, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(supportrequest.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(supportrequest.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supportrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SupportRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supportrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
