// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/scpbot/internal/ent/predicate"
	"github.com/go-faster/scpbot/internal/ent/syncstate"
)

// SyncStateUpdate is the builder for updating SyncState entities.
type SyncStateUpdate struct {
	config
	hooks    []Hook
	mutation *SyncStateMutation
}

// Where appends a list predicates to the SyncStateUpdate builder.
func (_u *SyncStateUpdate) Where(ps ...predicate.SyncState) *SyncStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *SyncStateUpdate) SetSource(v string) *SyncStateUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableSource(v *string) *SyncStateUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *SyncStateUpdate) SetLastSyncedAt(v time.Time) *SyncStateUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableLastSyncedAt(v *time.Time) *SyncStateUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *SyncStateUpdate) ClearLastSyncedAt() *SyncStateUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastCursor sets the "last_cursor" field.
func (_u *SyncStateUpdate) SetLastCursor(v string) *SyncStateUpdate {
	_u.mutation.SetLastCursor(v)
	return _u
}

// SetNillableLastCursor sets the "last_cursor" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableLastCursor(v *string) *SyncStateUpdate {
	if v != nil {
		_u.SetLastCursor(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncStateUpdate) SetStatus(v string) *SyncStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableStatus(v *string) *SyncStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SyncStateUpdate) SetError(v string) *SyncStateUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableError(v *string) *SyncStateUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SyncStateUpdate) ClearError() *SyncStateUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetDocumentCount sets the "document_count" field.
func (_u *SyncStateUpdate) SetDocumentCount(v int) *SyncStateUpdate {
	_u.mutation.ResetDocumentCount()
	_u.mutation.SetDocumentCount(v)
	return _u
}

// SetNillableDocumentCount sets the "document_count" field if the given value is not nil.
func (_u *SyncStateUpdate) SetNillableDocumentCount(v *int) *SyncStateUpdate {
	if v != nil {
		_u.SetDocumentCount(*v)
	}
	return _u
}

// AddDocumentCount adds value to the "document_count" field.
func (_u *SyncStateUpdate) AddDocumentCount(v int) *SyncStateUpdate {
	_u.mutation.AddDocumentCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncStateUpdate) SetUpdatedAt(v time.Time) *SyncStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SyncStateMutation object of the builder.
func (_u *SyncStateUpdate) Mutation() *SyncStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncStateUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := syncstate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SyncState.source": %w`, err)}
		}
	}
	return nil
}

func (_u *SyncStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncstate.Table, syncstate.Columns, sqlgraph.NewFieldSpec(syncstate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(syncstate.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(syncstate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(syncstate.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCursor(); ok {
		_spec.SetField(syncstate.FieldLastCursor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(syncstate.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(syncstate.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DocumentCount(); ok {
		_spec.SetField(syncstate.FieldDocumentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocumentCount(); ok {
		_spec.AddField(syncstate.FieldDocumentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncStateUpdateOne is the builder for updating a single SyncState entity.
type SyncStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncStateMutation
}

// SetSource sets the "source" field.
func (_u *SyncStateUpdateOne) SetSource(v string) *SyncStateUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableSource(v *string) *SyncStateUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *SyncStateUpdateOne) SetLastSyncedAt(v time.Time) *SyncStateUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableLastSyncedAt(v *time.Time) *SyncStateUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *SyncStateUpdateOne) ClearLastSyncedAt() *SyncStateUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetLastCursor sets the "last_cursor" field.
func (_u *SyncStateUpdateOne) SetLastCursor(v string) *SyncStateUpdateOne {
	_u.mutation.SetLastCursor(v)
	return _u
}

// SetNillableLastCursor sets the "last_cursor" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableLastCursor(v *string) *SyncStateUpdateOne {
	if v != nil {
		_u.SetLastCursor(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncStateUpdateOne) SetStatus(v string) *SyncStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableStatus(v *string) *SyncStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *SyncStateUpdateOne) SetError(v string) *SyncStateUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableError(v *string) *SyncStateUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *SyncStateUpdateOne) ClearError() *SyncStateUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetDocumentCount sets the "document_count" field.
func (_u *SyncStateUpdateOne) SetDocumentCount(v int) *SyncStateUpdateOne {
	_u.mutation.ResetDocumentCount()
	_u.mutation.SetDocumentCount(v)
	return _u
}

// SetNillableDocumentCount sets the "document_count" field if the given value is not nil.
func (_u *SyncStateUpdateOne) SetNillableDocumentCount(v *int) *SyncStateUpdateOne {
	if v != nil {
		_u.SetDocumentCount(*v)
	}
	return _u
}

// AddDocumentCount adds value to the "document_count" field.
func (_u *SyncStateUpdateOne) AddDocumentCount(v int) *SyncStateUpdateOne {
	_u.mutation.AddDocumentCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SyncStateUpdateOne) SetUpdatedAt(v time.Time) *SyncStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SyncStateMutation object of the builder.
func (_u *SyncStateUpdateOne) Mutation() *SyncStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncStateUpdate builder.
func (_u *SyncStateUpdateOne) Where(ps ...predicate.SyncState) *SyncStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncStateUpdateOne) Select(field string, fields ...string) *SyncStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncState entity.
func (_u *SyncStateUpdateOne) Save(ctx context.Context) (*SyncState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncStateUpdateOne) SaveX(ctx context.Context) *SyncState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SyncStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := syncstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SyncStateUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := syncstate.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SyncState.source": %w`, err)}
		}
	}
	return nil
}

func (_u *SyncStateUpdateOne) sqlSave(ctx context.Context) (_node *SyncState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(syncstate.Table, syncstate.Columns, sqlgraph.NewFieldSpec(syncstate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncstate.FieldID)
		for _, f := range fields {
			if !syncstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(syncstate.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(syncstate.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(syncstate.FieldLastSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCursor(); ok {
		_spec.SetField(syncstate.FieldLastCursor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(syncstate.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(syncstate.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.DocumentCount(); ok {
		_spec.SetField(syncstate.FieldDocumentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDocumentCount(); ok {
		_spec.AddField(syncstate.FieldDocumentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(syncstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SyncState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
