// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-faster/sisyphus/internal/ent/telegrampeer"
	"github.com/google/uuid"
)

// TelegramPeerCreate is the builder for creating a TelegramPeer entity.
type TelegramPeerCreate struct {
	config
	mutation *TelegramPeerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPeerType sets the "peer_type" field.
func (_c *TelegramPeerCreate) SetPeerType(v string) *TelegramPeerCreate {
	_c.mutation.SetPeerType(v)
	return _c
}

// SetPeerID sets the "peer_id" field.
func (_c *TelegramPeerCreate) SetPeerID(v int64) *TelegramPeerCreate {
	_c.mutation.SetPeerID(v)
	return _c
}

// SetAccessHash sets the "access_hash" field.
func (_c *TelegramPeerCreate) SetAccessHash(v int64) *TelegramPeerCreate {
	_c.mutation.SetAccessHash(v)
	return _c
}

// SetNillableAccessHash sets the "access_hash" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableAccessHash(v *int64) *TelegramPeerCreate {
	if v != nil {
		_c.SetAccessHash(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *TelegramPeerCreate) SetUsername(v string) *TelegramPeerCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableUsername(v *string) *TelegramPeerCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *TelegramPeerCreate) SetTitle(v string) *TelegramPeerCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableTitle(v *string) *TelegramPeerCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *TelegramPeerCreate) SetLastSeenAt(v time.Time) *TelegramPeerCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableLastSeenAt(v *time.Time) *TelegramPeerCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TelegramPeerCreate) SetCreatedAt(v time.Time) *TelegramPeerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableCreatedAt(v *time.Time) *TelegramPeerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TelegramPeerCreate) SetID(v uuid.UUID) *TelegramPeerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TelegramPeerCreate) SetNillableID(v *uuid.UUID) *TelegramPeerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the TelegramPeerMutation object of the builder.
func (_c *TelegramPeerCreate) Mutation() *TelegramPeerMutation {
	return _c.mutation
}

// Save creates the TelegramPeer in the database.
func (_c *TelegramPeerCreate) Save(ctx context.Context) (*TelegramPeer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TelegramPeerCreate) SaveX(ctx context.Context) *TelegramPeer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramPeerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramPeerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TelegramPeerCreate) defaults() {
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := telegrampeer.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := telegrampeer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := telegrampeer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TelegramPeerCreate) check() error {
	if _, ok := _c.mutation.PeerType(); !ok {
		return &ValidationError{Name: "peer_type", err: errors.New(`ent: missing required field "TelegramPeer.peer_type"`)}
	}
	if _, ok := _c.mutation.PeerID(); !ok {
		return &ValidationError{Name: "peer_id", err: errors.New(`ent: missing required field "TelegramPeer.peer_id"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "TelegramPeer.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TelegramPeer.created_at"`)}
	}
	return nil
}

func (_c *TelegramPeerCreate) sqlSave(ctx context.Context) (*TelegramPeer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TelegramPeerCreate) createSpec() (*TelegramPeer, *sqlgraph.CreateSpec) {
	var (
		_node = &TelegramPeer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(telegrampeer.Table, sqlgraph.NewFieldSpec(telegrampeer.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PeerType(); ok {
		_spec.SetField(telegrampeer.FieldPeerType, field.TypeString, value)
		_node.PeerType = value
	}
	if value, ok := _c.mutation.PeerID(); ok {
		_spec.SetField(telegrampeer.FieldPeerID, field.TypeInt64, value)
		_node.PeerID = value
	}
	if value, ok := _c.mutation.AccessHash(); ok {
		_spec.SetField(telegrampeer.FieldAccessHash, field.TypeInt64, value)
		_node.AccessHash = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(telegrampeer.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(telegrampeer.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(telegrampeer.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(telegrampeer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramPeer.Create().
//		SetPeerType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramPeerUpsert) {
//			SetPeerType(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramPeerCreate) OnConflict(opts ...sql.ConflictOption) *TelegramPeerUpsertOne {
	_c.conflict = opts
	return &TelegramPeerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramPeerCreate) OnConflictColumns(columns ...string) *TelegramPeerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramPeerUpsertOne{
		create: _c,
	}
}

type (
	// TelegramPeerUpsertOne is the builder for "upsert"-ing
	//  one TelegramPeer node.
	TelegramPeerUpsertOne struct {
		create *TelegramPeerCreate
	}

	// TelegramPeerUpsert is the "OnConflict" setter.
	TelegramPeerUpsert struct {
		*sql.UpdateSet
	}
)

// SetPeerType sets the "peer_type" field.
func (u *TelegramPeerUpsert) SetPeerType(v string) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldPeerType, v)
	return u
}

// UpdatePeerType sets the "peer_type" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdatePeerType() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldPeerType)
	return u
}

// SetPeerID sets the "peer_id" field.
func (u *TelegramPeerUpsert) SetPeerID(v int64) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldPeerID, v)
	return u
}

// UpdatePeerID sets the "peer_id" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdatePeerID() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldPeerID)
	return u
}

// AddPeerID adds v to the "peer_id" field.
func (u *TelegramPeerUpsert) AddPeerID(v int64) *TelegramPeerUpsert {
	u.Add(telegrampeer.FieldPeerID, v)
	return u
}

// SetAccessHash sets the "access_hash" field.
func (u *TelegramPeerUpsert) SetAccessHash(v int64) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldAccessHash, v)
	return u
}

// UpdateAccessHash sets the "access_hash" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdateAccessHash() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldAccessHash)
	return u
}

// AddAccessHash adds v to the "access_hash" field.
func (u *TelegramPeerUpsert) AddAccessHash(v int64) *TelegramPeerUpsert {
	u.Add(telegrampeer.FieldAccessHash, v)
	return u
}

// ClearAccessHash clears the value of the "access_hash" field.
func (u *TelegramPeerUpsert) ClearAccessHash() *TelegramPeerUpsert {
	u.SetNull(telegrampeer.FieldAccessHash)
	return u
}

// SetUsername sets the "username" field.
func (u *TelegramPeerUpsert) SetUsername(v string) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdateUsername() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldUsername)
	return u
}

// ClearUsername clears the value of the "username" field.
func (u *TelegramPeerUpsert) ClearUsername() *TelegramPeerUpsert {
	u.SetNull(telegrampeer.FieldUsername)
	return u
}

// SetTitle sets the "title" field.
func (u *TelegramPeerUpsert) SetTitle(v string) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdateTitle() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *TelegramPeerUpsert) ClearTitle() *TelegramPeerUpsert {
	u.SetNull(telegrampeer.FieldTitle)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *TelegramPeerUpsert) SetLastSeenAt(v time.Time) *TelegramPeerUpsert {
	u.Set(telegrampeer.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *TelegramPeerUpsert) UpdateLastSeenAt() *TelegramPeerUpsert {
	u.SetExcluded(telegrampeer.FieldLastSeenAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(telegrampeer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TelegramPeerUpsertOne) UpdateNewValues() *TelegramPeerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(telegrampeer.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(telegrampeer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TelegramPeerUpsertOne) Ignore() *TelegramPeerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramPeerUpsertOne) DoNothing() *TelegramPeerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramPeerCreate.OnConflict
// documentation for more info.
func (u *TelegramPeerUpsertOne) Update(set func(*TelegramPeerUpsert)) *TelegramPeerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramPeerUpsert{UpdateSet: update})
	}))
	return u
}

// SetPeerType sets the "peer_type" field.
func (u *TelegramPeerUpsertOne) SetPeerType(v string) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetPeerType(v)
	})
}

// UpdatePeerType sets the "peer_type" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdatePeerType() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdatePeerType()
	})
}

// SetPeerID sets the "peer_id" field.
func (u *TelegramPeerUpsertOne) SetPeerID(v int64) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetPeerID(v)
	})
}

// AddPeerID adds v to the "peer_id" field.
func (u *TelegramPeerUpsertOne) AddPeerID(v int64) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.AddPeerID(v)
	})
}

// UpdatePeerID sets the "peer_id" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdatePeerID() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdatePeerID()
	})
}

// SetAccessHash sets the "access_hash" field.
func (u *TelegramPeerUpsertOne) SetAccessHash(v int64) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetAccessHash(v)
	})
}

// AddAccessHash adds v to the "access_hash" field.
func (u *TelegramPeerUpsertOne) AddAccessHash(v int64) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.AddAccessHash(v)
	})
}

// UpdateAccessHash sets the "access_hash" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdateAccessHash() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateAccessHash()
	})
}

// ClearAccessHash clears the value of the "access_hash" field.
func (u *TelegramPeerUpsertOne) ClearAccessHash() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearAccessHash()
	})
}

// SetUsername sets the "username" field.
func (u *TelegramPeerUpsertOne) SetUsername(v string) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdateUsername() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *TelegramPeerUpsertOne) ClearUsername() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearUsername()
	})
}

// SetTitle sets the "title" field.
func (u *TelegramPeerUpsertOne) SetTitle(v string) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdateTitle() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *TelegramPeerUpsertOne) ClearTitle() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearTitle()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *TelegramPeerUpsertOne) SetLastSeenAt(v time.Time) *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *TelegramPeerUpsertOne) UpdateLastSeenAt() *TelegramPeerUpsertOne {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *TelegramPeerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramPeerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramPeerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TelegramPeerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TelegramPeerUpsertOne.ID is not supported by MySQL driver. Use TelegramPeerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TelegramPeerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TelegramPeerCreateBulk is the builder for creating many TelegramPeer entities in bulk.
type TelegramPeerCreateBulk struct {
	config
	err      error
	builders []*TelegramPeerCreate
	conflict []sql.ConflictOption
}

// Save creates the TelegramPeer entities in the database.
func (_c *TelegramPeerCreateBulk) Save(ctx context.Context) ([]*TelegramPeer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TelegramPeer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TelegramPeerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TelegramPeerCreateBulk) SaveX(ctx context.Context) []*TelegramPeer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelegramPeerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelegramPeerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TelegramPeer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TelegramPeerUpsert) {
//			SetPeerType(v+v).
//		}).
//		Exec(ctx)
func (_c *TelegramPeerCreateBulk) OnConflict(opts ...sql.ConflictOption) *TelegramPeerUpsertBulk {
	_c.conflict = opts
	return &TelegramPeerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TelegramPeerCreateBulk) OnConflictColumns(columns ...string) *TelegramPeerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TelegramPeerUpsertBulk{
		create: _c,
	}
}

// TelegramPeerUpsertBulk is the builder for "upsert"-ing
// a bulk of TelegramPeer nodes.
type TelegramPeerUpsertBulk struct {
	create *TelegramPeerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(telegrampeer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TelegramPeerUpsertBulk) UpdateNewValues() *TelegramPeerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(telegrampeer.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(telegrampeer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TelegramPeer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TelegramPeerUpsertBulk) Ignore() *TelegramPeerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TelegramPeerUpsertBulk) DoNothing() *TelegramPeerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TelegramPeerCreateBulk.OnConflict
// documentation for more info.
func (u *TelegramPeerUpsertBulk) Update(set func(*TelegramPeerUpsert)) *TelegramPeerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TelegramPeerUpsert{UpdateSet: update})
	}))
	return u
}

// SetPeerType sets the "peer_type" field.
func (u *TelegramPeerUpsertBulk) SetPeerType(v string) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetPeerType(v)
	})
}

// UpdatePeerType sets the "peer_type" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdatePeerType() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdatePeerType()
	})
}

// SetPeerID sets the "peer_id" field.
func (u *TelegramPeerUpsertBulk) SetPeerID(v int64) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetPeerID(v)
	})
}

// AddPeerID adds v to the "peer_id" field.
func (u *TelegramPeerUpsertBulk) AddPeerID(v int64) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.AddPeerID(v)
	})
}

// UpdatePeerID sets the "peer_id" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdatePeerID() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdatePeerID()
	})
}

// SetAccessHash sets the "access_hash" field.
func (u *TelegramPeerUpsertBulk) SetAccessHash(v int64) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetAccessHash(v)
	})
}

// AddAccessHash adds v to the "access_hash" field.
func (u *TelegramPeerUpsertBulk) AddAccessHash(v int64) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.AddAccessHash(v)
	})
}

// UpdateAccessHash sets the "access_hash" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdateAccessHash() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateAccessHash()
	})
}

// ClearAccessHash clears the value of the "access_hash" field.
func (u *TelegramPeerUpsertBulk) ClearAccessHash() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearAccessHash()
	})
}

// SetUsername sets the "username" field.
func (u *TelegramPeerUpsertBulk) SetUsername(v string) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdateUsername() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *TelegramPeerUpsertBulk) ClearUsername() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearUsername()
	})
}

// SetTitle sets the "title" field.
func (u *TelegramPeerUpsertBulk) SetTitle(v string) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdateTitle() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *TelegramPeerUpsertBulk) ClearTitle() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.ClearTitle()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *TelegramPeerUpsertBulk) SetLastSeenAt(v time.Time) *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *TelegramPeerUpsertBulk) UpdateLastSeenAt() *TelegramPeerUpsertBulk {
	return u.Update(func(s *TelegramPeerUpsert) {
		s.UpdateLastSeenAt()
	})
}

// Exec executes the query.
func (u *TelegramPeerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TelegramPeerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TelegramPeerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TelegramPeerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
