// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Chunk is the predicate function for chunk builders.
type Chunk func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// InvestigationJob is the predicate function for investigationjob builders.
type InvestigationJob func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// NotifySubscription is the predicate function for notifysubscription builders.
type NotifySubscription func(*sql.Selector)

// SupportRequest is the predicate function for supportrequest builders.
type SupportRequest func(*sql.Selector)

// SyncState is the predicate function for syncstate builders.
type SyncState func(*sql.Selector)

// TelegramMessage is the predicate function for telegrammessage builders.
type TelegramMessage func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserToken is the predicate function for usertoken builders.
type UserToken func(*sql.Selector)
