// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	AckNotificationOperation         OperationName = "AckNotification"
	ContextOperation                 OperationName = "Context"
	FetchURLOperation                OperationName = "FetchURL"
	GetFileOperation                 OperationName = "GetFile"
	GetHealthOperation               OperationName = "GetHealth"
	GetPendingNotificationsOperation OperationName = "GetPendingNotifications"
	NotifyEnrollOperation            OperationName = "NotifyEnroll"
	NotifyLinkOperation              OperationName = "NotifyLink"
	NotifyListSubscriptionsOperation OperationName = "NotifyListSubscriptions"
	NotifySubscribeOperation         OperationName = "NotifySubscribe"
	NotifyUnsubscribeOperation       OperationName = "NotifyUnsubscribe"
	SearchOperation                  OperationName = "Search"
)
