package agent

import (
	"encoding/json"

	"github.com/openai/openai-go/v3"
)

// toParamWithReasoning converts a completion into the param form fed back
// into the next request, carrying over the model's reasoning trace when the
// provider returned one. msg.ToParam alone drops it: it only copies fields
// the OpenAI schema knows about, and reasoning is a non-standard extension
// (OpenRouter/DeepSeek et al. park it in JSON.ExtraFields). Without this the
// model loses its own chain of thought between loop iterations and re-derives
// a plan from scratch every turn instead of continuing it.
func toParamWithReasoning(msg openai.ChatCompletionMessage) openai.ChatCompletionMessageParamUnion {
	param := msg.ToParam()
	if param.OfAssistant == nil {
		return param
	}
	if extra := reasoningExtraFields(msg); len(extra) > 0 {
		param.OfAssistant.SetExtraFields(extra)
	}
	return param
}

// reasoningExtraFields returns the wire field(s) needed to round-trip the
// model's reasoning trace into the next request. OpenRouter's docs say to
// prefer the structured "reasoning_details" over the plain "reasoning"
// string whenever a model returns it: some providers (e.g. Anthropic via
// OpenRouter) return encrypted/signed reasoning blocks there, and those
// "must match the outputs generated by the model during the original
// request" byte-for-byte to round-trip — a lossy string extraction (as
// ExtractReasoning does, for logging) is not good enough. reasoning_details
// is echoed back verbatim, unmodified. Only when a model returns no
// reasoning_details (some send just the plain string) does this fall back to
// ExtractReasoning's plain "reasoning" field.
func reasoningExtraFields(msg openai.ChatCompletionMessage) map[string]any {
	if f, ok := msg.JSON.ExtraFields["reasoning_details"]; ok {
		if raw := f.Raw(); raw != "" && raw != "null" {
			var details any
			if err := json.Unmarshal([]byte(raw), &details); err == nil {
				return map[string]any{"reasoning_details": details}
			}
		}
	}
	if r := ExtractReasoning(msg); r != "" {
		return map[string]any{"reasoning": r}
	}
	return nil
}

// ExtractReasoning extracts the model's reasoning trace from a completion.
// OpenRouter returns it as a top-level "reasoning" field on the message,
// which is not part of the OpenAI schema, so openai-go parks it in
// JSON.ExtraFields rather than a typed field. Returns "" for providers/models
// that send no reasoning.
//
// Note [respjson.Field.Valid] is deliberately not consulted: it reports false
// for every extra field (the parser only tracks presence for fields it
// knows), so gating on it would drop all reasoning.
func ExtractReasoning(msg openai.ChatCompletionMessage) string {
	f, ok := msg.JSON.ExtraFields["reasoning"]
	if !ok {
		return ""
	}
	raw := f.Raw()
	if raw == "" || raw == "null" {
		return ""
	}
	var s string
	if err := json.Unmarshal([]byte(raw), &s); err != nil {
		// Not a JSON string (some providers nest structured reasoning blocks);
		// the raw form still beats nothing for a debugger.
		return raw
	}
	return s
}
