// Code generated by ent, DO NOT EDIT.

package investigationjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-faster/sisyphus/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldID, id))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldStatus, v))
}

// Iterations applies equality check predicate on the "iterations" field. It's identical to IterationsEQ.
func Iterations(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldIterations, v))
}

// ToolsUsed applies equality check predicate on the "tools_used" field. It's identical to ToolsUsedEQ.
func ToolsUsed(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldToolsUsed, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContainsFold(FieldStatus, v))
}

// ReportIsNil applies the IsNil predicate on the "report" field.
func ReportIsNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIsNull(FieldReport))
}

// ReportNotNil applies the NotNil predicate on the "report" field.
func ReportNotNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotNull(FieldReport))
}

// IterationsEQ applies the EQ predicate on the "iterations" field.
func IterationsEQ(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldIterations, v))
}

// IterationsNEQ applies the NEQ predicate on the "iterations" field.
func IterationsNEQ(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldIterations, v))
}

// IterationsIn applies the In predicate on the "iterations" field.
func IterationsIn(vs ...int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldIterations, vs...))
}

// IterationsNotIn applies the NotIn predicate on the "iterations" field.
func IterationsNotIn(vs ...int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldIterations, vs...))
}

// IterationsGT applies the GT predicate on the "iterations" field.
func IterationsGT(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldIterations, v))
}

// IterationsGTE applies the GTE predicate on the "iterations" field.
func IterationsGTE(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldIterations, v))
}

// IterationsLT applies the LT predicate on the "iterations" field.
func IterationsLT(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldIterations, v))
}

// IterationsLTE applies the LTE predicate on the "iterations" field.
func IterationsLTE(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldIterations, v))
}

// ToolsUsedEQ applies the EQ predicate on the "tools_used" field.
func ToolsUsedEQ(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldToolsUsed, v))
}

// ToolsUsedNEQ applies the NEQ predicate on the "tools_used" field.
func ToolsUsedNEQ(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldToolsUsed, v))
}

// ToolsUsedIn applies the In predicate on the "tools_used" field.
func ToolsUsedIn(vs ...int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldToolsUsed, vs...))
}

// ToolsUsedNotIn applies the NotIn predicate on the "tools_used" field.
func ToolsUsedNotIn(vs ...int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldToolsUsed, vs...))
}

// ToolsUsedGT applies the GT predicate on the "tools_used" field.
func ToolsUsedGT(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldToolsUsed, v))
}

// ToolsUsedGTE applies the GTE predicate on the "tools_used" field.
func ToolsUsedGTE(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldToolsUsed, v))
}

// ToolsUsedLT applies the LT predicate on the "tools_used" field.
func ToolsUsedLT(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldToolsUsed, v))
}

// ToolsUsedLTE applies the LTE predicate on the "tools_used" field.
func ToolsUsedLTE(v int) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldToolsUsed, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.FieldNotNull(FieldCompletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvestigationJob) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvestigationJob) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvestigationJob) predicate.InvestigationJob {
	return predicate.InvestigationJob(sql.NotPredicates(p))
}
